/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.orgManagersWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.donationDealer.DonationDealer;
import StudentSale.deliveryAgent.DeliveryAgent;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sahithreddy
 */
public class ManageDeliveryAgentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryAgentJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private Organization org;
    private User userLogged;
    private static final Logger logger = Logger.getLogger(ManageDeliveryAgentJPanel.class.getName());
    
    public ManageDeliveryAgentJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork, Organization org, User userLogged) {
        initComponents();
        
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.org = org;
        this.userLogged = userLogged;
        this.cityNetwork = cityNetwork;
        
        populateDeliveryVolunteers();
        populateCityHeader();
    }
    
    private void populateCityHeader(){
        lblheadercityName.setText(cityNetwork.getCityName().name());
    }

    public void populateDeliveryVolunteers() {
        
        DefaultTableModel model = (DefaultTableModel) DeliveryAgentListLbl.getModel();
        model.setRowCount(0);
        int count = 0;
        for (DeliveryAgent deliveryAgent : org.getDeliveryVolunteerDirectory().getDeliveryVolunteers()) {

            count++;
            Object[] row = new Object[8];
            row[0] = count;
            row[1] = deliveryAgent;
            row[2] = deliveryAgent.getUserName();
            row[3] = deliveryAgent.getPassword();
            row[4] = deliveryAgent.getAddress();
            row[5] = deliveryAgent.getPhoneNo();
            row[6] = deliveryAgent.getEmail();
            row[7] = deliveryAgent.getCreatedBy();

            model.addRow(row);
        }
        deliveryAgentCountLbl.setText(String.valueOf(org.getDeliveryVolunteerDirectory().getDeliveryVolunteers().size()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLbl = new javax.swing.JLabel();
        orgheaderLbl = new javax.swing.JLabel();
        deliveryAGENTLbl = new javax.swing.JLabel();
        deliveryAgentCountLbl = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveryAgentListLbl = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        backButtonjButton = new javax.swing.JButton();
        lblheadercityTag = new javax.swing.JLabel();
        lblheadercityName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Manage Delivery Agents");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 40, 600, 35));

        orgheaderLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgheaderLbl.setText("Count :");
        add(orgheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 416, -1, -1));

        deliveryAGENTLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deliveryAGENTLbl.setText("Delivery Volunteer's List");
        add(deliveryAGENTLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, -1, -1));

        deliveryAgentCountLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deliveryAgentCountLbl.setText("0");
        add(deliveryAgentCountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 416, 28, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 416, 87, 30));

        DeliveryAgentListLbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S-No", "Name", "User Name", "Password", "Address", "MobileNo", "Email", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DeliveryAgentListLbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 899, 270));

        btnCreate.setText("Create >");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 416, 118, 30));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 416, 93, 30));

        backButtonjButton.setText("< < Back");
        backButtonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonjButtonActionPerformed(evt);
            }
        });
        add(backButtonjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 40, -1, -1));

        lblheadercityTag.setText("City:");
        add(lblheadercityTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 40, -1, 30));
        add(lblheadercityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = DeliveryAgentListLbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            DeliveryAgent deliveryAgent = (DeliveryAgent) DeliveryAgentListLbl.getValueAt(selectedRow, 1);
            org.getDeliveryVolunteerDirectory().getDeliveryVolunteers().remove(deliveryAgent);
            JOptionPane.showMessageDialog(null, "Delivery Volunteer deleted successfully");
            logger.log(Level.INFO, "Delivery Volunteer Profile deleted");
            populateDeliveryVolunteers();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateDeliveryAgentJPanel panel = new CreateDeliveryAgentJPanel(userProcessJpanel, ecoSystem, cityNetwork, org, userLogged);
        //          userProcessContainer.remove(this);
        userProcessJpanel.add("CreateNewDeliveryVolunteerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.next(userProcessJpanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = DeliveryAgentListLbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            DeliveryAgent deliveryAgent = (DeliveryAgent) DeliveryAgentListLbl.getValueAt(selectedRow, 1);
            UpdateDeliveryAgentJPanel updateDeliveryVolunteerJPanel = new UpdateDeliveryAgentJPanel(userProcessJpanel, ecoSystem, cityNetwork, org, deliveryAgent, userLogged);
            userProcessJpanel.add("UpdateDeliveryVolunteerJPanel", updateDeliveryVolunteerJPanel);
            CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
            layout.next(userProcessJpanel);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void backButtonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonjButtonActionPerformed
        // TODO add your handling code here:

        userProcessJpanel.remove(this);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.previous(userProcessJpanel);
    }//GEN-LAST:event_backButtonjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DeliveryAgentListLbl;
    private javax.swing.JButton backButtonjButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel deliveryAGENTLbl;
    private javax.swing.JLabel deliveryAgentCountLbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblheadercityName;
    private javax.swing.JLabel lblheadercityTag;
    private javax.swing.JLabel orgheaderLbl;
    // End of variables declaration//GEN-END:variables
}
