package userinterface.systemAdminWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.enums.OrganizationType;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.ValidateInputs;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class CreateNewOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewOrganizationJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userLogged;
    private static final Logger logger = Logger.getLogger(CreateNewOrganizationJPanel.class.getName());
    private String imagePath = Constants.DEFAULT_ORGANIZATION_IMAGE_PATH;
    
    public CreateNewOrganizationJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        
        imageLbl.setSize(126, 139);
        poupulateOrganizationTypes();
        setDefaultPhoto();
    }

    private void poupulateOrganizationTypes() {
        
        orgTypeCmbx.removeAllItems();
        
        String[] organizationTypes = OrganizationType.getOrganizationTypesArray();
        for(String organizationType:organizationTypes) {
            orgTypeCmbx.addItem(organizationType);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        phonNumTxtFld = new javax.swing.JTextField();
        headerLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        nameTxtFld = new javax.swing.JTextField();
        addLbl = new javax.swing.JLabel();
        addTxtFld = new javax.swing.JTextField();
        imageLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        emailTxtFld = new javax.swing.JTextField();
        phonNumLbl = new javax.swing.JLabel();
        orgTypeLbl = new javax.swing.JLabel();
        orgTypeCmbx = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("DesktopIcon.background"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        phonNumTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonNumTxtFldActionPerformed(evt);
            }
        });
        add(phonNumTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 216, 234, -1));

        headerLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Create New Organization");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 34, 415, 34));

        nameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("Name :");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 134, 122, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 350, -1, -1));

        nameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFldActionPerformed(evt);
            }
        });
        add(nameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 131, 234, -1));

        addLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLbl.setText("Address :");
        add(addLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 260, 122, -1));

        addTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtFldActionPerformed(evt);
            }
        });
        add(addTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 257, 234, -1));

        imageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(imageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 126, 139));

        emailLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLbl.setText("Email :");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 178, 122, -1));

        uploadBtn.setText("upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        emailTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFldActionPerformed(evt);
            }
        });
        add(emailTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 175, 234, -1));

        phonNumLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        phonNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phonNumLbl.setText("Phone No :");
        add(phonNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 219, 122, -1));

        orgTypeLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        orgTypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orgTypeLbl.setText("Organization Type :");
        add(orgTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 298, -1, -1));

        orgTypeCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTypeCmbxActionPerformed(evt);
            }
        });
        add(orgTypeCmbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 298, 172, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Back buttton pressed");
        userProcessJpanel.remove(this);

        Component[] components = userProcessJpanel.getComponents();
        ManageOrganizationsJPanel manageOrganizationsJPanel = (ManageOrganizationsJPanel) components[components.length-1];
        manageOrganizationsJPanel.populateOrganizations();

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Save buttton pressed");
        if(isDataEnteredValid()) {

            if(EmailHelper.isEmailAlreadyExisted(ecoSystem, emailTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            
            if(PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phonNumTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }

            String name = nameTxtFld.getText();
            String emailAddress = emailTxtFld.getText();
            String phoneNum = phonNumTxtFld.getText();
            String address = addTxtFld.getText();
            OrganizationType organizationType = OrganizationType.valueOf((String) orgTypeCmbx.getSelectedItem());

            Organization org = new Organization(name, organizationType, address, phoneNum, emailAddress, imagePath,
                new Date(), new Date(), userLogged.getName(), userLogged.getName());
            cityNetwork.getOrganizationDirectory().getOrganizations().add(org);

            JOptionPane.showMessageDialog(this, "Successfully saved new Organization");
            resetUi();
        }else{
            JOptionPane.showMessageDialog(this, "Error saving new Organization. Please insert correct input.");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nameTxtFld.getText()) && 
                ValidateInputs.isEmailValid(emailTxtFld.getText()) 
                && ValidateInputs.isPhoneNumberValid(phonNumTxtFld.getText())
                && ValidateInputs.isAddressValid(addTxtFld.getText()))  {
           return true; 
        }
        return false;
    }
    
    private void resetUi() {
        nameTxtFld.setText("");
        emailTxtFld.setText("");
        phonNumTxtFld.setText("");
        addTxtFld.setText("");
        orgTypeCmbx.setSelectedIndex(0);
        setDefaultPhoto();
    }
    
    private void setDefaultPhoto() {
        setPhoto(getClass().getResource(Constants.DEFAULT_ORGANIZATION_IMAGE_PATH).getPath());
    }    
    
    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(),4);
        imageLbl.setIcon(new ImageIcon(photoResized));
    }
    
    private void orgTypeCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTypeCmbxActionPerformed
    }//GEN-LAST:event_orgTypeCmbxActionPerformed

    private void nameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isNameValid(nameLbl.getText()) && nameTxtFld.getText().length() < 8 ){
                   JOptionPane.showMessageDialog(this, "Enter Name correctly");

       }
        
    }//GEN-LAST:event_nameTxtFldActionPerformed

    private void emailTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isEmailValid(emailTxtFld.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailTxtFldActionPerformed

    private void phonNumTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonNumTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isPhoneNumberValid(phonNumTxtFld.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phonNumTxtFldActionPerformed

    private void addTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtFldActionPerformed
        // TODO add your handling code here:
        if(!ValidateInputs.isAddressValid(addTxtFld.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addTxtFldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTxtFld;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JComboBox<String> orgTypeCmbx;
    private javax.swing.JLabel orgTypeLbl;
    private javax.swing.JLabel phonNumLbl;
    private javax.swing.JTextField phonNumTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
