package userinterface.systemAdminWorkArea;

import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.std.Student;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class CreateNewStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewStudentJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private static final Logger logger = Logger.getLogger(CreateNewStudentJPanel.class.getName());
    private String imagePath = Constants.DEFAULT_PROFILE_IMAGE_PATH;
    
    public CreateNewStudentJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        ImageLbl.setSize(126, 139);
        setDefaultPhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLbl = new javax.swing.JLabel();
        passwrdLbl = new javax.swing.JLabel();
        addTxtFld = new javax.swing.JTextField();
        passwrdTxtFild = new javax.swing.JTextField();
        ImageLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        emailTxtFld = new javax.swing.JTextField();
        phneNumLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        phneNumTxtFld = new javax.swing.JTextField();
        headerLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        usrNmeTxtFld = new javax.swing.JTextField();
        usrNameLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("DesktopIcon.background"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLbl.setText("Address :");
        add(addLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 343, 122, -1));

        passwrdLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        passwrdLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwrdLbl.setText("Password :");
        add(passwrdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 220, 122, -1));

        addTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtFldActionPerformed(evt);
            }
        });
        add(addTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 340, 234, -1));

        passwrdTxtFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwrdTxtFildActionPerformed(evt);
            }
        });
        add(passwrdTxtFild, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 217, 234, -1));

        ImageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(ImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 34, 126, 139));

        emailLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLbl.setText("Email :");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 261, 122, -1));

        uploadBtn.setText("upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 191, -1, -1));

        emailTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFldActionPerformed(evt);
            }
        });
        add(emailTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 258, 234, -1));

        phneNumLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        phneNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phneNumLbl.setText("Phone No :");
        add(phneNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 302, 122, -1));

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        phneNumTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phneNumTxtFldActionPerformed(evt);
            }
        });
        add(phneNumTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 299, 234, -1));

        headerLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Create New Student");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 34, 415, 34));

        nameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("Name :");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 134, 122, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 413, -1, -1));

        usrNmeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrNmeTxtFldActionPerformed(evt);
            }
        });
        add(usrNmeTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 176, 234, -1));

        usrNameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        usrNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usrNameLbl.setText("User Name :");
        add(usrNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 179, 122, -1));

        nameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFldActionPerformed(evt);
            }
        });
        add(nameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 131, 234, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void resetUi() {
        nameTxtFld.setText("");
        usrNmeTxtFld.setText("");
        passwrdTxtFild.setText("");
        emailTxtFld.setText("");
        phneNumTxtFld.setText("");
        addTxtFld.setText("");
        setDefaultPhoto();
    }
    
    private void setDefaultPhoto() {
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }

    private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(ImageLbl.getWidth(), ImageLbl.getHeight(),4);
        ImageLbl.setIcon(new ImageIcon(photoResized));
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        logger.log(Level.INFO, "Back button pressed");
        userProcessJpanel.remove(this);

        Component[] components = userProcessJpanel.getComponents();
        ManageStudentsJpanel manageDonorsJpanel = (ManageStudentsJpanel) components[components.length-1];
        manageDonorsJpanel.populateDonors();

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Save button pressed");
        if(isDataEnteredValid()) {

            if(UserNameHelper.isUserNameAlreadyExisted(ecoSystem, usrNmeTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "UserName already Exists in the Ecosystem.");
                return;
            }
            if(EmailHelper.isEmailAlreadyExisted(ecoSystem, emailTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            if(PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phneNumTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }

            String name = nameTxtFld.getText();
            String userName = usrNmeTxtFld.getText();
            String password = passwrdTxtFild.getText();
            String emailAddress = emailTxtFld.getText();
            String phoneNum = phneNumTxtFld.getText();
            String address = addTxtFld.getText();

            Student student = new Student(name, phoneNum, emailAddress, address, userName, password, StudentRole.Student, imagePath,
                new Date(), new Date(), userLogged.getName(), userLogged.getName());
            ecoSystem.getDonorsDirectory().getDonors().add(student);

            JOptionPane.showMessageDialog(this, "Successfully saved new Donor");
            resetUi();
        }else{
            JOptionPane.showMessageDialog(this, "Error saving new Donor. Please check required input.");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void nameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isNameValid(nameTxtFld.getText())){
                   JOptionPane.showMessageDialog(this, "Enter Name correctly");

       }
    }//GEN-LAST:event_nameTxtFldActionPerformed

    private void usrNmeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrNmeTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isUsernameValid(usrNmeTxtFld.getText())){
                   JOptionPane.showMessageDialog(this, "enter UserName correctly");

       }
    }//GEN-LAST:event_usrNmeTxtFldActionPerformed

    private void passwrdTxtFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwrdTxtFildActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isPasswordValid(passwrdTxtFild.getText()) ){
                   JOptionPane.showMessageDialog(this, "enter password correctly");

       }
    }//GEN-LAST:event_passwrdTxtFildActionPerformed

    private void emailTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isEmailValid(emailTxtFld.getText()) ){
                   JOptionPane.showMessageDialog(this, "enter Email correctly");

       }
    }//GEN-LAST:event_emailTxtFldActionPerformed

    private void phneNumTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phneNumTxtFldActionPerformed
        // TODO add your handling code here:
        
         if( !ValidateInputs.isPhoneNumberValid(phneNumTxtFld.getText())){
                   JOptionPane.showMessageDialog(this, "enter Phonenumber correctly");

       }
    }//GEN-LAST:event_phneNumTxtFldActionPerformed

    private void addTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isPasswordValid(addTxtFld.getText()) ){
                   JOptionPane.showMessageDialog(this, "Enter Address correctly");
       } 
    }//GEN-LAST:event_addTxtFldActionPerformed

    private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nameTxtFld.getText()) && ValidateInputs.isUsernameValid(usrNmeTxtFld.getText()) && 
                ValidateInputs.isEmailValid(emailTxtFld.getText()) && ValidateInputs.isPhoneNumberValid(phneNumTxtFld.getText())
                && ValidateInputs.isPasswordValid(passwrdTxtFild.getText()) && ValidateInputs.isAddressValid(addTxtFld.getText()))  {
           return true; 
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLbl;
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTxtFld;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JLabel passwrdLbl;
    private javax.swing.JTextField passwrdTxtFild;
    private javax.swing.JLabel phneNumLbl;
    private javax.swing.JTextField phneNumTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JLabel usrNameLbl;
    private javax.swing.JTextField usrNmeTxtFld;
    // End of variables declaration//GEN-END:variables
}
