/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemAdminWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.organization.OrganizationManager;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshila
 */
public class ManageOrganizationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationsJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userLogged;
    
    public ManageOrganizationsJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        
        populateOrganizations();
    }

    public void populateOrganizations() {
        
        DefaultTableModel model = (DefaultTableModel) tblOrgList.getModel();
        model.setRowCount(0);
        int count=0;
        for(Organization org:cityNetwork.getOrganizationDirectory().getOrganizations()) {
            
            count++;
            Object[] row = new Object[7];
            row[0]=count;
            row[1]=org;
            row[2]=org.getOrganizationType().name();
            row[3]=org.getAddress();
            row[4]=org.getPhoneNo();
            row[5]=org.getEmail();
            row[6]=org.getCreatedBy();
                    
            model.addRow(row);
        }
        orgCountLbl.setText(String.valueOf(cityNetwork.getOrganizationDirectory().getOrganizations().size()));
        DefaultTableModel managersModel = (DefaultTableModel) tblOrgManagersJtable.getModel();
        managersModel.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgManagerCountLbl = new javax.swing.JLabel();
        btnManageOrgManagers = new javax.swing.JButton();
        headerManagersLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrgManagersJtable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        UpdateMangersBtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        deleteMangersBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        CreateMangrsBtn = new javax.swing.JButton();
        headerLbl = new javax.swing.JLabel();
        orgheaderLbl = new javax.swing.JLabel();
        orgLbl = new javax.swing.JLabel();
        orgCountLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrgList = new javax.swing.JTable();
        orgManagerheaderLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgManagerCountLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgManagerCountLbl.setText("0");
        add(orgManagerCountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 654, 19, -1));

        btnManageOrgManagers.setText("Manage Organization Managers");
        btnManageOrgManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgManagersActionPerformed(evt);
            }
        });
        add(btnManageOrgManagers, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 325, -1, 30));

        headerManagersLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerManagersLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerManagersLbl.setText("Manage Organization Managers");
        add(headerManagersLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 373, 384, 35));

        tblOrgManagersJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S-No", "Manager Name", "UserName", "Password", "Phone No", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrgManagersJtable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 889, 191));

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 325, 87, 30));

        createBtn.setText("Create >");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 325, 118, 30));

        UpdateMangersBtn.setText("Update");
        UpdateMangersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMangersBtnActionPerformed(evt);
            }
        });
        add(UpdateMangersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 648, 93, 30));

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 325, 93, 30));

        deleteMangersBtn.setText("Delete");
        deleteMangersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMangersBtnActionPerformed(evt);
            }
        });
        add(deleteMangersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 648, 87, 30));

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 35, -1, -1));

        CreateMangrsBtn.setText("Create >");
        CreateMangrsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMangrsBtnActionPerformed(evt);
            }
        });
        add(CreateMangrsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 648, 118, 30));

        headerLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Manage Organizations");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 35, 600, 35));

        orgheaderLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgheaderLbl.setText("Count :");
        add(orgheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 88, -1, -1));

        orgLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgLbl.setText("Organizations List");
        add(orgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 88, -1, -1));

        orgCountLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgCountLbl.setText("0");
        add(orgCountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 88, 19, -1));

        tblOrgList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S-No", "Organization Name", "OrganizationType", "Address", "MobileNo", "Email", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrgList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrgListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrgList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 889, 184));

        orgManagerheaderLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgManagerheaderLbl.setText("Count :");
        add(orgManagerheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 654, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrgManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgManagersActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrgList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization selectedOrganization = (Organization) tblOrgList.getValueAt(selectedRow, 1);
            DefaultTableModel managersModel = (DefaultTableModel) tblOrgManagersJtable.getModel();
            managersModel.setRowCount(0);
            int employeeCount=0;
            for(OrganizationManager orgManager:selectedOrganization.getOrgManagerDirectory().getOrgManagers()) {
                employeeCount++;
                Object[] row = new Object[7];
                row[0] = employeeCount;
                row[1] = orgManager;
                row[2] = orgManager.getUserName();
                row[3] = orgManager.getPassword();
                row[4] = orgManager.getPhoneNo();
                row[5] = orgManager.getEmail();
                row[6] = orgManager.getAddress();

                managersModel.addRow(row);
            }
            orgManagerCountLbl.setText(String.valueOf(selectedOrganization.getOrgManagerDirectory().getOrgManagers().size()));
        }
    }//GEN-LAST:event_btnManageOrgManagersActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrgList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization selectedOrganization = (Organization) tblOrgList.getValueAt(selectedRow, 1);
            cityNetwork.getOrganizationDirectory().getOrganizations().remove(selectedOrganization);
            JOptionPane.showMessageDialog(null, "Organization deleted successfully");

            populateOrganizations();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateNewOrganizationJPanel panel = new CreateNewOrganizationJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged);
        //          userProcessContainer.remove(this);
        userProcessJpanel.add("CreateNewOrganizationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.next(userProcessJpanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void UpdateMangersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMangersBtnActionPerformed
        // TODO add your handling code here:
        int selectedManager = tblOrgManagersJtable.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to Update");
            return;
        }
        DefaultTableModel organizationManagerModel = (DefaultTableModel) tblOrgManagersJtable.getModel();
        OrganizationManager orgManager = (OrganizationManager) organizationManagerModel.getValueAt(selectedManager, 1);

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("UpdateOrganizationManagerPanel", new UpdateOrganizationManagerJPanel(userProcessJpanel, ecoSystem, orgManager, userLogged));
        cardLayout.next(userProcessJpanel);

    }//GEN-LAST:event_UpdateMangersBtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrgList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization selectedOrganization = (Organization) tblOrgList.getValueAt(selectedRow, 1);
            UpdateOrganizationJPanel updateOrganizationJPanel = new UpdateOrganizationJPanel(userProcessJpanel, ecoSystem, selectedOrganization, userLogged);
            userProcessJpanel.add("UpdateOrganizationPanel", updateOrganizationJPanel);
            CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
            layout.next(userProcessJpanel);
        }
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void deleteMangersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMangersBtnActionPerformed
        // TODO add your handling code here:
        int selectedManager = tblOrgManagersJtable.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to delete");
            return;
        }
        DefaultTableModel organizationManagerModel = (DefaultTableModel) tblOrgManagersJtable.getModel();
        OrganizationManager orgManager = (OrganizationManager) organizationManagerModel.getValueAt(selectedManager, 1);

        int selectedRow = tblOrgList.getSelectedRow();
        DefaultTableModel organizationsModel = (DefaultTableModel) tblOrgList.getModel();
        Organization selectedOrganization = (Organization) organizationsModel.getValueAt(selectedRow, 1);
        selectedOrganization.getOrgManagerDirectory().getOrgManagers().remove(orgManager);
        JOptionPane.showMessageDialog(this, "Successfully deleted Manager");
        populateOrganizations();
    }//GEN-LAST:event_deleteMangersBtnActionPerformed

    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessJpanel.remove(this);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void CreateMangrsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMangrsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrgList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Organization to add Managers");
            return;
        } else {
            DefaultTableModel organizationsModel = (DefaultTableModel) tblOrgList.getModel();
            Organization selectedOrganization = (Organization) organizationsModel.getValueAt(selectedRow, 1);
            CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
            userProcessJpanel.add("SysAdminCreateManagerPanel", new CreateOrganizationManagerJPanel(userProcessJpanel, ecoSystem, selectedOrganization, userLogged));
            cardLayout.next(userProcessJpanel);

        }
    }//GEN-LAST:event_CreateMangrsBtnActionPerformed

    private void tblOrgListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrgListMouseClicked
        // TODO add your handling code here:
        btnManageOrgManagersActionPerformed(null);
    }//GEN-LAST:event_tblOrgListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateMangrsBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton UpdateMangersBtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnManageOrgManagers;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteMangersBtn;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel headerManagersLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel orgCountLbl;
    private javax.swing.JLabel orgLbl;
    private javax.swing.JLabel orgManagerCountLbl;
    private javax.swing.JLabel orgManagerheaderLbl;
    private javax.swing.JLabel orgheaderLbl;
    private javax.swing.JTable tblOrgList;
    private javax.swing.JTable tblOrgManagersJtable;
    // End of variables declaration//GEN-END:variables
}
