package userinterface.systemAdminWorkArea;

import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.packingAgent.PackingAgent;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshila
 */
public class ManagePackingAgentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePackingAgentJpanel
     */
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private User userLogged;

    public ManagePackingAgentJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        populatePackingAgents();
    }

    public void populatePackingAgents() {
        DefaultTableModel model = (DefaultTableModel) tblPackingAgentList.getModel();
        model.setRowCount(0);
        int count = 0;
        for (PackingAgent packingAgent : ecoSystem.getPackingAgentsDirectory().getPackingAgents()) {

            count++;
            Object[] row = new Object[6];
            row[0] = count;
            row[1] = packingAgent;
            row[2] = packingAgent.getAddress();
            row[3] = packingAgent.getPhoneNo();
            row[4] = packingAgent.getEmail();
            row[5] = packingAgent.getCreatedBy();
            model.addRow(row);
        }
        packingAgentCountjLabel.setText(String.valueOf(ecoSystem.getPackingAgentsDirectory().getPackingAgents().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerjLabel = new javax.swing.JLabel();
        organizationheaderjLabel = new javax.swing.JLabel();
        donorsjLabel = new javax.swing.JLabel();
        packingAgentCountjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPackingAgentList = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        createPackingAgentJButton = new javax.swing.JButton();
        packingAgentDeletejButton = new javax.swing.JButton();
        updatePackingAgentjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerjLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel.setText("Manage Packing Agent");
        add(headerjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 40, 600, 35));

        organizationheaderjLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        organizationheaderjLabel.setText("Count :");
        add(organizationheaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        donorsjLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        donorsjLabel.setText("Packing Agent List");
        add(donorsjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, -1, -1));

        packingAgentCountjLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        packingAgentCountjLabel.setText("0");
        add(packingAgentCountjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 28, -1));

        tblPackingAgentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S-No", "Name", "Address", "Mobile No", "Email", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPackingAgentList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 899, 270));

        backjButton.setText("< < Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 25, -1, -1));

        createPackingAgentJButton.setText("Create");
        createPackingAgentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPackingAgentJButtonActionPerformed(evt);
            }
        });
        add(createPackingAgentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, -1, -1));

        packingAgentDeletejButton.setText("Delete");
        packingAgentDeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packingAgentDeletejButtonActionPerformed(evt);
            }
        });
        add(packingAgentDeletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        updatePackingAgentjButton.setText("Update");
        updatePackingAgentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePackingAgentjButtonActionPerformed(evt);
            }
        });
        add(updatePackingAgentjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessJpanel.remove(this);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.previous(userProcessJpanel);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void createPackingAgentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPackingAgentJButtonActionPerformed
        CreatePackingAgentJPanel panel = new CreatePackingAgentJPanel(userProcessJpanel, ecoSystem, userLogged);
        userProcessJpanel.add("CreatePackingAgentJPanel", panel);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.next(userProcessJpanel);
    }//GEN-LAST:event_createPackingAgentJButtonActionPerformed

    private void packingAgentDeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packingAgentDeletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPackingAgentList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            PackingAgent selectedPackingAgent = (PackingAgent) tblPackingAgentList.getValueAt(selectedRow, 1);
            ecoSystem.getPackingAgentsDirectory().getPackingAgents().remove(selectedPackingAgent);
            JOptionPane.showMessageDialog(null, "Packing Agent deleted successfully");
            populatePackingAgents();
        }
    }//GEN-LAST:event_packingAgentDeletejButtonActionPerformed

    private void updatePackingAgentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePackingAgentjButtonActionPerformed
        int selectedRow = tblPackingAgentList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            PackingAgent packingAgent = (PackingAgent) tblPackingAgentList.getValueAt(selectedRow, 1);
            UpdatePackingAgentJPanel updatePackingAgentJPanel = new UpdatePackingAgentJPanel(userProcessJpanel, ecoSystem, packingAgent, userLogged);
            userProcessJpanel.add("UpdatePackingAgentJPanel", updatePackingAgentJPanel);
            CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
            layout.next(userProcessJpanel);
        }
    }//GEN-LAST:event_updatePackingAgentjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createPackingAgentJButton;
    private javax.swing.JLabel donorsjLabel;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel organizationheaderjLabel;
    private javax.swing.JLabel packingAgentCountjLabel;
    private javax.swing.JButton packingAgentDeletejButton;
    private javax.swing.JTable tblPackingAgentList;
    private javax.swing.JButton updatePackingAgentjButton;
    // End of variables declaration//GEN-END:variables
}
