/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemAdminWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.donationDealer.DonationDealer;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshila
 */
public class ManageDonationDealerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDonationDealerJPanel
     */
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userLogged;
    private static final Logger logger = Logger.getLogger(ManageDonationDealerJPanel.class.getName());

    public ManageDonationDealerJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        populateDonationDealers();
    }

    public void populateDonationDealers() {

        DefaultTableModel model = (DefaultTableModel) tbldonationDonarList.getModel();
        model.setRowCount(0);
        int count = 0;
        for (DonationDealer donationDealer : cityNetwork.getCityOfficialsDirectory().getCityOfficials()) {

            count++;
            Object[] row = new Object[8];
            row[0] = count;
            row[1] = donationDealer;
            row[2] = donationDealer.getUserName();
            row[3] = donationDealer.getPassword();
            row[4] = donationDealer.getAddress();
            row[5] = donationDealer.getPhoneNo();
            row[6] = donationDealer.getEmail();
            row[7] = donationDealer.getCreatedBy();

            model.addRow(row);
        }
        dealerdonarCountLbl.setText(String.valueOf(cityNetwork.getCityOfficialsDirectory().getCityOfficials().size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBtn = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        headerlbl = new javax.swing.JLabel();
        orgheaderLbl = new javax.swing.JLabel();
        dealerdonarlLbl = new javax.swing.JLabel();
        dealerdonarCountLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldonationDonarList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setText("Create >");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 118, 30));

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 93, 30));

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 40, -1, -1));

        headerlbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlbl.setText("Manage Donation Dealer");
        add(headerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 40, 600, 35));

        orgheaderLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        orgheaderLbl.setText("Count :");
        add(orgheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 416, -1, -1));

        dealerdonarlLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        dealerdonarlLbl.setText("Donation Dealer's List");
        add(dealerdonarlLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, -1, -1));

        dealerdonarCountLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        dealerdonarCountLbl.setText("0");
        add(dealerdonarCountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 416, 28, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 87, 30));

        tbldonationDonarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S-No", "Name", "User Name", "Password", "Address", "MobileNo", "Email", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldonationDonarList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 899, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateDonationDealersJPanel panel = new CreateDonationDealersJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged);
        userProcessJpanel.add("CreateDonationDealerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.next(userProcessJpanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbldonationDonarList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            DonationDealer cityOfficial = (DonationDealer) tbldonationDonarList.getValueAt(selectedRow, 1);
            UpdateDonationDealerJPanel updateDonationDealerJPanel = new UpdateDonationDealerJPanel(userProcessJpanel, ecoSystem, cityOfficial, userLogged);
            userProcessJpanel.add("UpdateDonationDealerPanel", updateDonationDealerJPanel);
            CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
            layout.next(userProcessJpanel);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Back button pressed");
        userProcessJpanel.remove(this);
        CardLayout layout = (CardLayout) userProcessJpanel.getLayout();
        layout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbldonationDonarList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            DonationDealer cityOfficial = (DonationDealer) tbldonationDonarList.getValueAt(selectedRow, 1);
            cityNetwork.getCityOfficialsDirectory().getCityOfficials().remove(cityOfficial);
            JOptionPane.showMessageDialog(null, "Donation Dealer deleted successfully");

            populateDonationDealers();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel dealerdonarCountLbl;
    private javax.swing.JLabel dealerdonarlLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel headerlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgheaderLbl;
    private javax.swing.JTable tbldonationDonarList;
    // End of variables declaration//GEN-END:variables
}
