package userinterface.systemAdminWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author harshila
 */
public class SysAdminManageCityJPanel extends javax.swing.JPanel {

    /**
     * Create SystemAdminManageCityJPanel
     */
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userLogged;
    
    public SysAdminManageCityJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork,User userLogged) {
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        initComponents();
        
        lblcity.setText(cityNetwork.getCityName().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        headerjLabel = new javax.swing.JLabel();
        manageOrganizationsjButton = new javax.swing.JButton();
        manageDonorsjButton = new javax.swing.JButton();
        manageCityOfficialsjButton = new javax.swing.JButton();
        lblcity = new javax.swing.JLabel();
        managePackingAgentjButton1 = new javax.swing.JButton();
        manageDriverjButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backjButton.setText("< < Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 56, -1, -1));

        headerjLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel.setText("Area Donation Management");
        add(headerjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 46, 450, 39));

        manageOrganizationsjButton.setText("Manage Area >>");
        manageOrganizationsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationsjButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 213, -1));

        manageDonorsjButton.setText("Manage Student >>");
        manageDonorsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDonorsjButtonActionPerformed(evt);
            }
        });
        add(manageDonorsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 226, -1));

        manageCityOfficialsjButton.setText("Manage Dealers >>");
        manageCityOfficialsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCityOfficialsjButtonActionPerformed(evt);
            }
        });
        add(manageCityOfficialsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 222, -1));
        add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 91, 80, 22));

        managePackingAgentjButton1.setText("Manage Packing Agents >>");
        managePackingAgentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePackingAgentjButton1ActionPerformed(evt);
            }
        });
        add(managePackingAgentjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        manageDriverjButton2.setText("Manage Drivers >>");
        manageDriverjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDriverjButton2ActionPerformed(evt);
            }
        });
        add(manageDriverjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        userProcessJpanel.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        Component[] components = userProcessJpanel.getComponents();
        SysAdminHomeJPanel sysAdminHomeJPanel = (SysAdminHomeJPanel) components[components.length-1];
        sysAdminHomeJPanel.populateSysAdmins();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void manageOrganizationsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationsjButtonActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminOrganizationManagePanel", new ManageOrganizationsJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageOrganizationsjButtonActionPerformed

    private void manageDonorsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDonorsjButtonActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminDonorManagePanel", new ManageStudentsJpanel(userProcessJpanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageDonorsjButtonActionPerformed

    private void manageCityOfficialsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCityOfficialsjButtonActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("SysAdminCityOfficialManagePanel", new ManageDonationDealerJPanel(userProcessJpanel, ecoSystem, cityNetwork, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageCityOfficialsjButtonActionPerformed

    private void managePackingAgentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePackingAgentjButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("ManagePackingAgentPanel", new ManagePackingAgentJPanel(userProcessJpanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_managePackingAgentjButton1ActionPerformed

    private void manageDriverjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDriverjButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("ManageDriverPanel", new ManageDriverJPanel(userProcessJpanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_manageDriverjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblcity;
    private javax.swing.JButton manageCityOfficialsjButton;
    private javax.swing.JButton manageDonorsjButton;
    private javax.swing.JButton manageDriverjButton2;
    private javax.swing.JButton manageOrganizationsjButton;
    private javax.swing.JButton managePackingAgentjButton1;
    // End of variables declaration//GEN-END:variables
}
