/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.deliveryAgentWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.io.IOException;
/**
 *
 * @author sishwathoka
 */
public class DeliveryAgentHomeJPanel extends javax.swing.JPanel {

    private JPanel userProcessJPanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private CityNetwork cityNetwork;
    private Organization org;
    
    /**
     * Creates new form DeliveryVolunteerHomeJPanel
     */
    public DeliveryAgentHomeJPanel(JPanel userProcessJPanel, EcoSystem ecoSystem, CityNetwork cityNetwork, Organization org, User userLogged) {
        initComponents();
        this.userProcessJPanel = userProcessJPanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        this.cityNetwork = cityNetwork;
        this.org = org;
       
        labelcityName.setText(cityNetwork.getCityName().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        updateMyProfileBtn = new javax.swing.JButton();
        manageMyDeliveriesBtn = new javax.swing.JButton();
        labelCityTag = new javax.swing.JLabel();
        labelcityName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitle.setText("Delivery Agent Home Page");
        add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 37, -1, 27));

        updateMyProfileBtn.setText("Update my Profile");
        updateMyProfileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateMyProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMyProfileBtnActionPerformed(evt);
            }
        });
        add(updateMyProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 131, -1));

        manageMyDeliveriesBtn.setText("Manage My Deliveries");
        manageMyDeliveriesBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        manageMyDeliveriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMyDeliveriesBtnActionPerformed(evt);
            }
        });
        add(manageMyDeliveriesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        labelCityTag.setText("City:");
        add(labelCityTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 37, -1, 30));
        add(labelcityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 37, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/finaldelivery.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 579, 312));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateMyProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMyProfileBtnActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("UpdateDeliveryVolunteerProfileJPanel", new UpdateDeliveryAgentProfileJPanel(userProcessJPanel,ecoSystem,userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_updateMyProfileBtnActionPerformed

    private void manageMyDeliveriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMyDeliveriesBtnActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("ManageMyDeliveriesJPanel", new ManageMyDeliveriesJPanel(userProcessJPanel, ecoSystem, cityNetwork, org, userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_manageMyDeliveriesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCityTag;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelcityName;
    private javax.swing.JButton manageMyDeliveriesBtn;
    private javax.swing.JButton updateMyProfileBtn;
    // End of variables declaration//GEN-END:variables
}
