/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.serviceAgent.ServiceAgent;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import StudentSale.helper.ValidateInputs;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class CreateServiceAgentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateServiceAgentJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private User userAccount;
    private CityNetwork cityNetwork;
    //add default image
    private String imagepath = Constants.DEFAULT_PROFILE_IMAGE_PATH;
    
    public CreateServiceAgentJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, User userAccount, CityNetwork cityNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount  = userAccount;
        this.cityNetwork = cityNetwork;
        picHolderLbl.setSize(126, 139);
        setDefaultPhoto();
        headerCityNameLbl.setText(cityNetwork.getCityName().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headclean = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        maillbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JLabel();
        pswrdlbl = new javax.swing.JLabel();
        picHolderLbl = new javax.swing.JLabel();
        uploadbutton = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        phoneNumbtxt = new javax.swing.JTextField();
        emailIdtext = new javax.swing.JTextField();
        addtext = new javax.swing.JTextField();
        usernametxt = new javax.swing.JTextField();
        passwrdtext = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        headerCityNameLbl = new javax.swing.JLabel();
        headerCityTagLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headclean.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        headclean.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headclean.setText("Create New Service Agent");
        add(headclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 25, 342, 32));

        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namelbl.setText("Name:");
        add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 111, 90, 30));

        addresslbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addresslbl.setText("Address:");
        add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 205, 90, 33));

        maillbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maillbl.setText("Email Id:");
        add(maillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 256, 90, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Phone Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 168, -1, -1));

        usernamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernamelbl.setText("UserName:");
        add(usernamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 298, 90, 30));

        pswrdlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pswrdlbl.setText("Password:");
        add(pswrdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 346, 90, 27));

        picHolderLbl.setText("     <Image>");
        picHolderLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picHolderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 115, 111, 104));

        uploadbutton.setText("Upload");
        uploadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbuttonActionPerformed(evt);
            }
        });
        add(uploadbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 231, -1, -1));

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 112, 143, 30));

        phoneNumbtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumbtxtActionPerformed(evt);
            }
        });
        add(phoneNumbtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 162, 143, 30));

        emailIdtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdtextActionPerformed(evt);
            }
        });
        add(emailIdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 250, 143, 30));

        addtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtextActionPerformed(evt);
            }
        });
        add(addtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 207, 143, 30));

        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 298, 143, 30));

        passwrdtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwrdtextActionPerformed(evt);
            }
        });
        add(passwrdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 346, 143, 30));

        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 388, -1, -1));

        backbutton.setText("< < Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 37, -1, -1));
        add(headerCityNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 30, 130, 30));

        headerCityTagLbl.setText("City:");
        add(headerCityTagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 30, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
           if(isDataEnteredValid()) {
            String name = nametxt.getText();
            String userName = usernametxt.getText();
            String address=addtext.getText();
            
            String password = passwrdtext.getText();
            String emailAddress = emailIdtext.getText();
            String phoneNum = phoneNumbtxt.getText();

            ServiceAgent serviceAgent = new ServiceAgent(name, phoneNum, emailAddress, address,userName, password, StudentRole.ServiceAgent,imagepath,
                new Date(), new Date(), userAccount.getName(), userAccount.getName());
            cityNetwork.getCleanersDirectory().getCleaners().add(serviceAgent);

            JOptionPane.showMessageDialog(this, "Successfully Saved ");
            resetUi();
        }else{
            JOptionPane.showMessageDialog(this, "Error! Please enter valid values");
        }
    }//GEN-LAST:event_savebuttonActionPerformed

    private void uploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbuttonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagepath = selectedFile.getAbsolutePath();
            setPhoto(imagepath);
        }
    }//GEN-LAST:event_uploadbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] components = userProcessContainer.getComponents();
        ManageServiceAgentJPanel manageCleanersJPanel = (ManageServiceAgentJPanel) components[components.length-1];
        manageCleanersJPanel.populateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void passwrdtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwrdtextActionPerformed
        if( !ValidateInputs.isPasswordValid(passwrdtext.getText())){
                   JOptionPane.showMessageDialog(this, "Enter password correctly(minimum 8 digits)");

       }
    }//GEN-LAST:event_passwrdtextActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
       if(!ValidateInputs.isNameValid(nametxt.getText())){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_nametxtActionPerformed

    private void phoneNumbtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumbtxtActionPerformed
        if( !ValidateInputs.isPhoneNumberValid(phoneNumbtxt.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phoneNumbtxtActionPerformed

    private void addtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtextActionPerformed
        if(!ValidateInputs.isAddressValid(addtext.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addtextActionPerformed

    private void emailIdtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdtextActionPerformed
        if( !ValidateInputs.isEmailValid(emailIdtext.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailIdtextActionPerformed

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        if(!ValidateInputs.isUsernameValid(usernametxt.getText())){
           JOptionPane.showMessageDialog(this, "Enter Username correctly");
       }
    }//GEN-LAST:event_usernametxtActionPerformed
   
    private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nametxt.getText()) && ValidateInputs.isUsernameValid(usernametxt.getText()) && 
                ValidateInputs.isEmailValid(emailIdtext.getText()) && ValidateInputs.isPhoneNumberValid(phoneNumbtxt.getText())
                && ValidateInputs.isPasswordValid(passwrdtext.getText()) && ValidateInputs.isAddressValid(addtext.getText()))  {
         return true; 
        }
        return false;
    } 
    
    
    private void resetUi() {
        
        nametxt.setText("");
        usernametxt.setText("");
        addtext.setText("");
        passwrdtext.setText("");
        emailIdtext.setText("");
        phoneNumbtxt.setText("");
        setDefaultPhoto();
        
    }
    
    //have to make changes
     private void setDefaultPhoto() {
        
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }

    private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(picHolderLbl.getWidth(), picHolderLbl.getHeight(),4);
        picHolderLbl.setIcon(new ImageIcon(photoResized));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JTextField addtext;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField emailIdtext;
    private javax.swing.JLabel headclean;
    private javax.swing.JLabel headerCityNameLbl;
    private javax.swing.JLabel headerCityTagLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel maillbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField passwrdtext;
    private javax.swing.JTextField phoneNumbtxt;
    private javax.swing.JLabel picHolderLbl;
    private javax.swing.JLabel pswrdlbl;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton uploadbutton;
    private javax.swing.JLabel usernamelbl;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
