/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.enums.OrganizationType;
import StudentSale.helper.Constants;
import StudentSale.helper.ValidateInputs;
import StudentSale.organization.Organization;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class CreateOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private CityNetwork cityNetwork;
    private EcoSystem ecoSystem;
    private User userAccount;
    
     private String imagePath = Constants.DEFAULT_ORGANIZATION_IMAGE_PATH;
    
    public CreateOrganizationJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, User userAccount, CityNetwork cityNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cityNetwork = cityNetwork;
        this.userAccount = userAccount;
        poupulateOrganizationTypes();
        citytxt.setText(cityNetwork.getCityName().name());
        picHolderJlbl.setSize(126, 139);
        setDefaultPhoto();
        
        
    }
    
    private void setDefaultPhoto() {
        
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }
    private void poupulateOrganizationTypes() {
        
        orgtype.removeAllItems();
        
        String[] organizationTypes = OrganizationType.getOrganizationTypesArray();
        for(String organizationType:organizationTypes) {
            orgtype.addItem(organizationType);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgbckbtn = new javax.swing.JButton();
        orglbl = new javax.swing.JLabel();
        typelbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        numlbl = new javax.swing.JLabel();
        maillbl = new javax.swing.JLabel();
        orgNametxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        numtxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        orgtype = new javax.swing.JComboBox<>();
        picHolderJlbl = new javax.swing.JLabel();
        uploadbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        citytxt = new javax.swing.JLabel();
        citylbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgbckbtn.setText("Back");
        orgbckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgbckbtnActionPerformed(evt);
            }
        });
        add(orgbckbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        orglbl.setText("Organization Name:");
        add(orglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 28));

        typelbl.setText("Organization Type:");
        add(typelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        addresslbl.setText("Address:");
        add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        numlbl.setText("Phone Number:");
        add(numlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        maillbl.setText("Email Id:");
        add(maillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        orgNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgNametxtActionPerformed(evt);
            }
        });
        add(orgNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 133, 31));

        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });
        add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 133, 31));

        numtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtxtActionPerformed(evt);
            }
        });
        add(numtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 133, 31));

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 133, 31));

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        orgtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgtypeActionPerformed(evt);
            }
        });
        add(orgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 133, 31));

        picHolderJlbl.setText("<Image>");
        picHolderJlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picHolderJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 108, 119));

        uploadbtn.setText("Upload");
        uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbtnActionPerformed(evt);
            }
        });
        add(uploadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Create New Organization");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 350, 29));
        add(citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 6, 130, 30));

        citylbl.setText("City:");
        add(citylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 6, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orgNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgNametxtActionPerformed
        if(!ValidateInputs.isNameValid(orgNametxt.getText())){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_orgNametxtActionPerformed

    private void orgbckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgbckbtnActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] components = userProcessContainer.getComponents();
        ManageOrganizationJPanel manageOrgJPanel = (ManageOrganizationJPanel) components[components.length-1];
        manageOrgJPanel.populateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_orgbckbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        if(isDataEnteredValid()){
            String orgName = orgNametxt.getText();
            
            String address = addresstxt.getText();
            String emailAddress = idtxt.getText();
            String phoneNum = numtxt.getText();
            OrganizationType organizationType = OrganizationType.valueOf((String) orgtype.getSelectedItem());

              Organization org = new Organization(orgName, organizationType, address, phoneNum, emailAddress, imagePath,
                new Date(), new Date(), userAccount.getName(), userAccount.getName());
            cityNetwork.getOrganizationDirectory().getOrganizations().add(org);

            JOptionPane.showMessageDialog(this, "Successfully Saved");
            resetUi();
        }else{
            JOptionPane.showMessageDialog(this, "Error! Please enter valid values");
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void uploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbtnActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadbtnActionPerformed

    private void numtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtxtActionPerformed
        if( !ValidateInputs.isPhoneNumberValid(numtxt.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_numtxtActionPerformed

    private void orgtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgtypeActionPerformed

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        if(!ValidateInputs.isAddressValid(addresstxt.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addresstxtActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        if( !ValidateInputs.isEmailValid(idtxt.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_idtxtActionPerformed
     private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(picHolderJlbl.getWidth(), picHolderJlbl.getHeight(),4);
        picHolderJlbl.setIcon(new ImageIcon(photoResized));
    } 
    
    private boolean isDataEnteredValid() {
        
        if(!orgNametxt.getText().isEmpty() && orgNametxt.getText().matches("^[a-zA-Z0-9 ']+$") &&
                !addresstxt.getText().isEmpty() && !numtxt.getText().isEmpty() && 
                numtxt.getText().matches("^[0-9]+$") && numtxt.getText().length()==10 &&
                idtxt.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")){
            return true;
        }
        return false;
    }
    
    private void resetUi() {
       orgNametxt.setText("");
    
       addresstxt.setText("");
       idtxt.setText("");
       numtxt.setText("");
       
       setDefaultPhoto();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JLabel citylbl;
    private javax.swing.JLabel citytxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel maillbl;
    private javax.swing.JLabel numlbl;
    private javax.swing.JTextField numtxt;
    private javax.swing.JTextField orgNametxt;
    private javax.swing.JButton orgbckbtn;
    private javax.swing.JLabel orglbl;
    private javax.swing.JComboBox<String> orgtype;
    private javax.swing.JLabel picHolderJlbl;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel typelbl;
    private javax.swing.JButton uploadbtn;
    // End of variables declaration//GEN-END:variables
}
