/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import StudentSale.organization.OrganizationManager;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.nio.file.Paths;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class CreateOrgManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateOrgManagerJPanel
     */
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private Organization org;
    private CityNetwork cityNetwork;
    private User userLogged;
    
    private String imagePath = Constants.DEFAULT_PROFILE_IMAGE_PATH;
    
    public CreateOrgManagerJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, CityNetwork cityNetwork, Organization org, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem; 
        this.org = org;
        this.cityNetwork = cityNetwork;
        this.userLogged = userLogged;
        
        picHolderjLabel.setSize(126, 139);
        setDefaultPhoto();
        
        populateCityHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgbnkbtn = new javax.swing.JButton();
        orgheaderlbl = new javax.swing.JLabel();
        picHolderjLabel = new javax.swing.JLabel();
        uploadjButton = new javax.swing.JButton();
        nameorg = new javax.swing.JTextField();
        nameorglbl = new javax.swing.JLabel();
        userlblorg = new javax.swing.JLabel();
        usernameorg = new javax.swing.JTextField();
        pswrdorg = new javax.swing.JTextField();
        pswrdorglbl = new javax.swing.JLabel();
        emailorglbl = new javax.swing.JLabel();
        emailorg = new javax.swing.JTextField();
        phoneorg = new javax.swing.JTextField();
        numorglbl = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        addresslbl = new javax.swing.JLabel();
        orgsave = new javax.swing.JButton();
        citynamelbl = new javax.swing.JLabel();
        cityorg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("DesktopIcon.background"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgbnkbtn.setText("< < Back");
        orgbnkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgbnkbtnActionPerformed(evt);
            }
        });
        add(orgbnkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, -1, -1));

        orgheaderlbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        orgheaderlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orgheaderlbl.setText("Create New Organization Manager");
        add(orgheaderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 34, 415, 34));

        picHolderjLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picHolderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 126, 139));

        uploadjButton.setText("upload");
        uploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadjButtonActionPerformed(evt);
            }
        });
        add(uploadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        nameorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameorgActionPerformed(evt);
            }
        });
        add(nameorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 234, 30));

        nameorglbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameorglbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameorglbl.setText("Name :");
        add(nameorglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 122, -1));

        userlblorg.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        userlblorg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userlblorg.setText("User Name :");
        add(userlblorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 122, -1));

        usernameorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameorgActionPerformed(evt);
            }
        });
        add(usernameorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 234, 30));

        pswrdorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrdorgActionPerformed(evt);
            }
        });
        add(pswrdorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 234, 30));

        pswrdorglbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pswrdorglbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pswrdorglbl.setText("Password :");
        add(pswrdorglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 122, -1));

        emailorglbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        emailorglbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailorglbl.setText("Email :");
        add(emailorglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 122, -1));

        emailorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailorgActionPerformed(evt);
            }
        });
        add(emailorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 234, 30));

        phoneorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneorgActionPerformed(evt);
            }
        });
        add(phoneorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 234, 30));

        numorglbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        numorglbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numorglbl.setText("Phone No :");
        add(numorglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 122, -1));

        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });
        add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 234, 30));

        addresslbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addresslbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addresslbl.setText("Address :");
        add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 122, -1));

        orgsave.setText("Save");
        orgsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgsaveActionPerformed(evt);
            }
        });
        add(orgsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));
        add(citynamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 34, 130, 30));

        cityorg.setText("City:");
        add(cityorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 34, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void populateCityHeader(){
        for(CityNetwork cn : ecoSystem.getCityNetworkDirectory().getCityNetworks()){
            for(Organization org : cn.getOrganizationDirectory().getOrganizations()){
                if(org.getOrganizationName().equals(org.getOrganizationName())){
                    citynamelbl.setText(cn.getCityName().name());
                }
            }        
        }        
    }
    
    private void setDefaultPhoto() {
        
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }
    
    private void orgbnkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgbnkbtnActionPerformed
        // TODO add your handling code here:
        userProcessJpanel.remove(this);

        Component[] components = userProcessJpanel.getComponents();
        ManageOrganizationJPanel manageOrganizationsJPanel = (ManageOrganizationJPanel) components[components.length-1];
        manageOrganizationsJPanel.populateData();

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_orgbnkbtnActionPerformed

    private void uploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadjButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadjButtonActionPerformed
   private void resetUi() {
        
        nameorg.setText("");
        usernameorg.setText("");
        pswrdorg.setText("");
        emailorg.setText("");
        phoneorg.setText("");
        addresstxt.setText("");
        
        setDefaultPhoto();
    }
    
    private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(picHolderjLabel.getWidth(), picHolderjLabel.getHeight(),4);
        picHolderjLabel.setIcon(new ImageIcon(photoResized));
    }
    private void orgsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgsaveActionPerformed
        // TODO add your handling code here:
        if(isDataEnteredValid()) {
            
            if(UserNameHelper.isUserNameAlreadyExisted(ecoSystem, usernameorg.getText())) {
                JOptionPane.showMessageDialog(this, "UserName already Exists in the Ecosystem.");
                return;
            }
            if(EmailHelper.isEmailAlreadyExisted(ecoSystem, emailorg.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            if(PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phoneorg.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }
            
            String name = nameorg.getText();
            String userName = usernameorg.getText();
            String password = pswrdorg.getText();
            String emailAddress = emailorg.getText();
            String phoneNum = phoneorg.getText();
            String address = addresstxt.getText();

            OrganizationManager orgManager = new OrganizationManager(name, phoneNum, emailAddress, address, userName, password, StudentRole.OrgManager, imagePath,
                new Date(), new Date(), userLogged.getName(), userLogged.getName());
            org.getOrgManagerDirectory().getOrgManagers().add(orgManager);

            JOptionPane.showMessageDialog(this, "Successfully saved new Organization Manager");
            resetUi();
        }else{
            JOptionPane.showMessageDialog(this, "Error saving new Organization Manager. Please check DataTypes");
        }
    }//GEN-LAST:event_orgsaveActionPerformed

    private void nameorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameorgActionPerformed
        if(!ValidateInputs.isNameValid(nameorg.getText()) || nameorg.getText().length() < 8){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_nameorgActionPerformed

    private void usernameorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameorgActionPerformed
        if(!ValidateInputs.isUsernameValid(usernameorg.getText())){
           JOptionPane.showMessageDialog(this, "Enter Username correctly");
       }
    }//GEN-LAST:event_usernameorgActionPerformed

    private void pswrdorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswrdorgActionPerformed
        if( !ValidateInputs.isPasswordValid(pswrdorg.getText())){
                   JOptionPane.showMessageDialog(this, "Enter password correctly(minimum 8 digits)");

       }
    }//GEN-LAST:event_pswrdorgActionPerformed

    private void emailorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailorgActionPerformed
        if( !ValidateInputs.isEmailValid(emailorg.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailorgActionPerformed

    private void phoneorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneorgActionPerformed
        if( !ValidateInputs.isPhoneNumberValid(phoneorg.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phoneorgActionPerformed

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        if(!ValidateInputs.isAddressValid(addresstxt.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addresstxtActionPerformed
   private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nameorg.getText()) && ValidateInputs.isUsernameValid(usernameorg.getText()) && 
                ValidateInputs.isEmailValid(emailorg.getText()) && ValidateInputs.isPhoneNumberValid(phoneorg.getText())
                && ValidateInputs.isPasswordValid(pswrdorg.getText()) && ValidateInputs.isAddressValid(addresstxt.getText()))  {
        return true; 
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JLabel citynamelbl;
    private javax.swing.JLabel cityorg;
    private javax.swing.JTextField emailorg;
    private javax.swing.JLabel emailorglbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameorg;
    private javax.swing.JLabel nameorglbl;
    private javax.swing.JLabel numorglbl;
    private javax.swing.JButton orgbnkbtn;
    private javax.swing.JLabel orgheaderlbl;
    private javax.swing.JButton orgsave;
    private javax.swing.JTextField phoneorg;
    private javax.swing.JLabel picHolderjLabel;
    private javax.swing.JTextField pswrdorg;
    private javax.swing.JLabel pswrdorglbl;
    private javax.swing.JButton uploadjButton;
    private javax.swing.JLabel userlblorg;
    private javax.swing.JTextField usernameorg;
    // End of variables declaration//GEN-END:variables
}
