/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.organization.OrganizationManager;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshila
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewOrganizationJPanel
     */
        private JPanel userProcessContainer;
        private User userLogged;
        private EcoSystem ecoSystem;
        private CityNetwork cityNetwork;
        
    public ManageOrganizationJPanel(JPanel jpanel, User userLogged, EcoSystem ecoSystem, CityNetwork cityNetwork) {
        this.ecoSystem=ecoSystem;
        this.userLogged=userLogged;
        this.userProcessContainer=jpanel;
        this.cityNetwork=cityNetwork;
        initComponents();
        populateData();
        
        headercityNameLbl.setText(cityNetwork.getCityName().name());       
    }
    
    public void populateData(){
        DefaultTableModel model = (DefaultTableModel) manageOrgtable.getModel();
        model.setRowCount(0);
        int count=0;
        for(Organization org:cityNetwork.getOrganizationDirectory().getOrganizations()){
            count++;
            Object[] row = new Object[7];
            row[0]=count;
            row[1]=org;
            row[2]=org.getOrganizationType();
            row[3]=org.getAddress();
            row[4]=org.getPhoneNo();
            row[5]=org.getEmail();
            row[6]=org.getCreatedBy();
            
            model.addRow(row);
        }
        DefaultTableModel managersModel = (DefaultTableModel) managerOrgtable.getModel();
        managersModel.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgHeaderLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageOrgtable = new javax.swing.JTable();
        addOrgbutton = new javax.swing.JButton();
        updateOrgbutton = new javax.swing.JButton();
        deleteOrgbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        managerOrgtable = new javax.swing.JTable();
        orgManagerLbl = new javax.swing.JLabel();
        addManagerbutton = new javax.swing.JButton();
        updateManagerbutton = new javax.swing.JButton();
        deleteManagerbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        managerOrgbutton = new javax.swing.JButton();
        headercityNameLbl = new javax.swing.JLabel();
        headerCityTagLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgHeaderLbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        orgHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orgHeaderLbl.setText("Manage Organizations ");
        add(orgHeaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 301, 29));

        manageOrgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Organization Name", "Organization Type", "Address", "Mobile Number", "Email Id", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manageOrgtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageOrgtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manageOrgtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 903, 169));

        addOrgbutton.setText("Add");
        addOrgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgbuttonActionPerformed(evt);
            }
        });
        add(addOrgbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, -1, -1));

        updateOrgbutton.setText("Update");
        updateOrgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrgbuttonActionPerformed(evt);
            }
        });
        add(updateOrgbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        deleteOrgbutton.setText("Delete");
        deleteOrgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgbuttonActionPerformed(evt);
            }
        });
        add(deleteOrgbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        managerOrgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Manager Name", "Mobile Number", "Email Id", "Address", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(managerOrgtable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 903, 180));

        orgManagerLbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        orgManagerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orgManagerLbl.setText("Manage Organization Manager");
        add(orgManagerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 397, 41));

        addManagerbutton.setText("Add");
        addManagerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManagerbuttonActionPerformed(evt);
            }
        });
        add(addManagerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, -1, -1));

        updateManagerbutton.setText("Update");
        updateManagerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateManagerbuttonActionPerformed(evt);
            }
        });
        add(updateManagerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, -1, -1));

        deleteManagerbutton.setText("Delete");
        deleteManagerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteManagerbuttonActionPerformed(evt);
            }
        });
        add(deleteManagerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        backbutton.setText("< < Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        managerOrgbutton.setText("Manage Organization Manager");
        managerOrgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerOrgbuttonActionPerformed(evt);
            }
        });
        add(managerOrgbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));
        add(headercityNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 130, 30));

        headerCityTagLbl.setText("City:");
        add(headerCityTagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addManagerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManagerbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Restaurant to add Managers");
            return;
        } else {
            DefaultTableModel organizationsModel = (DefaultTableModel) manageOrgtable.getModel();
            Organization selectedOrganization = (Organization) organizationsModel.getValueAt(selectedRow, 1);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("SysAdminCreateManagerPanel", new CreateOrgManagerJPanel(userProcessContainer, ecoSystem, cityNetwork, selectedOrganization, userLogged));
            cardLayout.next(userProcessContainer);

        }

    }//GEN-LAST:event_addManagerbuttonActionPerformed

    private void deleteOrgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization org = (Organization) manageOrgtable.getValueAt(selectedRow, 1);
            
            cityNetwork.getOrganizationDirectory().getOrganizations().remove(org);
           
            JOptionPane.showMessageDialog(null, "Organization deleted Successfully! ");
            populateData();
        }
    }//GEN-LAST:event_deleteOrgbuttonActionPerformed

    private void managerOrgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerOrgbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization org = (Organization) manageOrgtable.getValueAt(selectedRow, 1);
            DefaultTableModel managersModel = (DefaultTableModel) managerOrgtable.getModel();
            managersModel.setRowCount(0);
            int employeeCount=0;
            for(OrganizationManager orgManager:org.getOrgManagerDirectory().getOrgManagers()) {
                employeeCount++;
                Object[] row = new Object[7];
                row[0] = employeeCount;
                row[1] = orgManager;
                row[2] = orgManager.getPhoneNo();
                row[3] = orgManager.getEmail();
                row[4] = orgManager.getAddress();
                row[5] = orgManager.getUserName();
                row[6] = orgManager.getPassword();
                managersModel.addRow(row);
            }
        }
    }//GEN-LAST:event_managerOrgbuttonActionPerformed

    private void deleteManagerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteManagerbuttonActionPerformed
        // TODO add your handling code here:
        int selectedManager = managerOrgtable.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to delete");
            return;
        }
        DefaultTableModel managerModel = (DefaultTableModel) managerOrgtable.getModel();
        OrganizationManager orgManager = (OrganizationManager) managerOrgtable.getValueAt(selectedManager, 1);
        
        int selectedRow = manageOrgtable.getSelectedRow();
        DefaultTableModel orgManagerModel = (DefaultTableModel) manageOrgtable.getModel();
        Organization org = (Organization) orgManagerModel.getValueAt(selectedRow, 1);
    
        org.getOrgManagerDirectory().getOrgManagers().remove(orgManager);
        JOptionPane.showMessageDialog(this, "Successfully deleted Manager");
      
        populateData();
    
        
    }//GEN-LAST:event_deleteManagerbuttonActionPerformed

    private void updateManagerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateManagerbuttonActionPerformed
        // TODO add your handling code here:
        int selectedManager = managerOrgtable.getSelectedRow();
        if(selectedManager < 0) {
            JOptionPane.showMessageDialog(this, "Please select a manager to Update");
            return;
        }
        DefaultTableModel organizationManagerModel = (DefaultTableModel) managerOrgtable.getModel();
        OrganizationManager orgManager = (OrganizationManager) organizationManagerModel.getValueAt(selectedManager, 1);

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("UpdateOrganizationManagerPanel", new UpdateOrgManagerJPanel(userProcessContainer, ecoSystem, cityNetwork, orgManager, userLogged));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_updateManagerbuttonActionPerformed

    private void updateOrgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrgbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageOrgtable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        } else {
            Organization selectedOrganization = (Organization) manageOrgtable.getValueAt(selectedRow, 1);
            UpdateOrganizationJPanel updateOrganizationJPanel = new UpdateOrganizationJPanel(userProcessContainer, ecoSystem, cityNetwork, selectedOrganization, userLogged);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("UpdateOrganizationPanel", updateOrganizationJPanel);
    
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateOrgbuttonActionPerformed

    private void addOrgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgbuttonActionPerformed
        // TODO add your handling code here:
        CreateOrganizationJPanel panel = new CreateOrganizationJPanel(userProcessContainer, ecoSystem, userLogged,cityNetwork );
        //          userProcessContainer.remove(this);
        userProcessContainer.add("CreateNewOrganizationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addOrgbuttonActionPerformed

    private void manageOrgtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrgtableMouseClicked
        managerOrgbuttonActionPerformed(null);
    }//GEN-LAST:event_manageOrgtableMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addManagerbutton;
    private javax.swing.JButton addOrgbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deleteManagerbutton;
    private javax.swing.JButton deleteOrgbutton;
    private javax.swing.JLabel headerCityTagLbl;
    private javax.swing.JLabel headercityNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manageOrgtable;
    private javax.swing.JButton managerOrgbutton;
    private javax.swing.JTable managerOrgtable;
    private javax.swing.JLabel orgHeaderLbl;
    private javax.swing.JLabel orgManagerLbl;
    private javax.swing.JButton updateManagerbutton;
    private javax.swing.JButton updateOrgbutton;
    // End of variables declaration//GEN-END:variables
}
