/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.CollectionCenter;
import StudentSale.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshila
 */
public class ManageCollectionCenterJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private User userAccount;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private CollectionCenter foodbank;
    /**
     * Creates new form ManageFoodBankJPanel
     */
    public ManageCollectionCenterJPanel(JPanel userProcessContainer,User userAccount,
        EcoSystem ecoSystem, CityNetwork cityNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount=userAccount;
        this.cityNetwork = cityNetwork;
        this.ecoSystem=ecoSystem;
        populateData();
        headerCityNameLbl.setText(cityNetwork.getCityName().name());
    }
    
         public void populateData(){
                 DefaultTableModel manageCleanersModel = (DefaultTableModel) manageCollCentertbl.getModel();
                 manageCleanersModel.setRowCount(0);
                 int currentFoodbank=0;
                 
                 for(CollectionCenter foodbank:cityNetwork.getFoodBankDirectory().getFoodBanks()){
                     currentFoodbank++;
                     Object[] row = new Object[7];
                     row[0]=currentFoodbank;
                     row[1]=foodbank;
                     row[2]=foodbank.getLocation();
                    
                     manageCleanersModel.addRow(row);
                 }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backLbl = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageCollCentertbl = new javax.swing.JTable();
        deletebutton = new javax.swing.JButton();
        createbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        headerCityNameLbl = new javax.swing.JLabel();
        headerCityTagLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backLbl.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        backLbl.setText("Manage Collection Center");
        add(backLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 261, 32));

        backbutton.setText("< < Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 38, -1, -1));

        manageCollCentertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Collection Center Name", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageCollCentertbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 581, 169));

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        createbutton.setText("Create >");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });
        add(createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));
        add(headerCityNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 130, 30));

        headerCityTagLbl.setText("City:");
        add(headerCityTagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Create New Cleaners", new CreateCollectionCenterJPanel(userProcessContainer, userAccount, ecoSystem, cityNetwork));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_createbuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
         int selectedRow = manageCollCentertbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }else {
        CollectionCenter foodbank=(CollectionCenter) manageCollCentertbl.getValueAt(selectedRow, 1);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Update Food Bank", new UpdateCollectionCenterJPanel(userProcessContainer, ecoSystem, foodbank, userAccount));
        cardLayout.next(userProcessContainer);
        }
         
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
         int selectedRow=manageCollCentertbl.getSelectedRow();
         if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Food Bank to delete");
            return;
        }else{
             CollectionCenter foodbank=(CollectionCenter) manageCollCentertbl.getValueAt(selectedRow, 1);
             cityNetwork.getFoodBankDirectory().getFoodBanks().remove(foodbank);
             JOptionPane.showMessageDialog(null, "Successfully deleted Food Bank ");
      
            populateData();
            
            
         }
    }//GEN-LAST:event_deletebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLbl;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton createbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel headerCityNameLbl;
    private javax.swing.JLabel headerCityTagLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageCollCentertbl;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
