/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package userinterface.donationDealerWorkArea;


import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.serviceAgent.ServiceAgent;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import StudentSale.organization.OrganizationManager;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class UpdateServiceAgentJPanel extends javax.swing.JPanel {

    /** Creates new form UpdateServiceAgentJPanel */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private ServiceAgent serviceAgent;
    private User userAccount;
    private String imagePath;
    private CityNetwork citynetwork;
    
    public UpdateServiceAgentJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, CityNetwork citynetwork, ServiceAgent serviceAgent, User userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.citynetwork = citynetwork;
        this.serviceAgent=serviceAgent;
        this.userAccount  = userAccount;
        photoLabel.setSize(126, 139);
        populateData();
        
        populateCityHeader();
    }
    
    private void populateCityHeader(){
        headerCityNameLbl.setText(citynetwork.getCityName().name());
    }
    
    private void setDefaultPhoto() {
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }
    
    private void populateData(){
        nametext.setText(serviceAgent.getName());
        phoneNumText.setText(serviceAgent.getPhoneNo());
        emailIdText.setText(serviceAgent.getEmail());
        addrssText.setText(serviceAgent.getAddress());
        usrnametext.setText(serviceAgent.getUserName());
        psswordText.setText(serviceAgent.getPassword());
        imagePath =serviceAgent.getProfilePic();
        setPhoto(serviceAgent.getProfilePic());
        
    }
    
    private void setPhoto(String photo) {
        
        if(photo.equals(Constants.DEFAULT_PROFILE_IMAGE_PATH)) {
            ImageIcon pic = new ImageIcon(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
            Image photoResized = pic.getImage().getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(),4);
            photoLabel.setIcon(new ImageIcon(photoResized));
            return;
        }
 
        ImageIcon pic = new ImageIcon(photo);
        Image photoResized = pic.getImage().getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(),4);
        photoLabel.setIcon(new ImageIcon(photoResized));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        phoneNumText = new javax.swing.JTextField();
        emailIdText = new javax.swing.JTextField();
        nameTxt = new javax.swing.JLabel();
        addrssText = new javax.swing.JTextField();
        phoneNumLbl = new javax.swing.JLabel();
        usrnametext = new javax.swing.JTextField();
        emailIdTxt = new javax.swing.JLabel();
        psswordText = new javax.swing.JTextField();
        addrssLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        headerCityNameLbl = new javax.swing.JLabel();
        headerCityTagLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Update Service Agent");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 10, -1, 35));

        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });
        add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 148, -1));

        phoneNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTextActionPerformed(evt);
            }
        });
        add(phoneNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 148, -1));

        emailIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTextActionPerformed(evt);
            }
        });
        add(emailIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 148, -1));

        nameTxt.setText("Name:");
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        addrssText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrssTextActionPerformed(evt);
            }
        });
        add(addrssText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 148, -1));

        phoneNumLbl.setText("Phone Number:");
        add(phoneNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        usrnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnametextActionPerformed(evt);
            }
        });
        add(usrnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 148, -1));

        emailIdTxt.setText("Email Id:");
        add(emailIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        psswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswordTextActionPerformed(evt);
            }
        });
        add(psswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 148, -1));

        addrssLbl.setText("Address:");
        add(addrssLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        userNameLbl.setText("UserName:");
        add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        passLbl.setText("Password:");
        add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        photoLabel.setText("      <Image>");
        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 111, 120));

        uploadButton.setText("Edit Picture");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        backButton.setText("< < Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 23, -1, -1));
        add(headerCityNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 10, 130, 30));

        headerCityTagLbl.setText("City:");
        add(headerCityTagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 16, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if(isDataEnteredValid()) {
            
            if(!serviceAgent.getUserName().equals(usrnametext.getText()) && UserNameHelper.isUserNameAlreadyExisted(ecoSystem, usrnametext.getText())) {
                JOptionPane.showMessageDialog(this, "UserName already Exists in the Ecosystem.");
                return;
            }
            if(!serviceAgent.getEmail().equals(emailIdText.getText()) && EmailHelper.isEmailAlreadyExisted(ecoSystem, emailIdText.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            if(!serviceAgent.getPhoneNo().equals(phoneNumText.getText()) && PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phoneNumText.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }
            
            serviceAgent.setName(nametext.getText());
            serviceAgent.setPhoneNo(phoneNumText.getText());
            serviceAgent.setAddress(addrssText.getText());
            serviceAgent.setEmail(emailIdText.getText());
            serviceAgent.setPassword(psswordText.getText());
            serviceAgent.setUserName(usrnametext.getText());
            serviceAgent.setModifiedBy(userAccount.getName());
            serviceAgent.setLastUpdatedDate(new Date());

            JOptionPane.showMessageDialog(this, "Successfully Updated ");
        }else {
            JOptionPane.showMessageDialog(this, "Error! Please enter valid values");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] components = userProcessContainer.getComponents();
        ManageServiceAgentJPanel manageCleanersJPanel = (ManageServiceAgentJPanel) components[components.length-1];
        manageCleanersJPanel.populateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addrssTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrssTextActionPerformed
        if(!ValidateInputs.isAddressValid(addrssText.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addrssTextActionPerformed

    private void psswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswordTextActionPerformed
        if( !ValidateInputs.isPasswordValid(psswordText.getText())){
                   JOptionPane.showMessageDialog(this, "Enter password correctly(minimum 8 digits)");

       }
    }//GEN-LAST:event_psswordTextActionPerformed

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
       if(!ValidateInputs.isNameValid(nametext.getText())){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_nametextActionPerformed

    private void phoneNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTextActionPerformed
        if( !ValidateInputs.isPhoneNumberValid(phoneNumText.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phoneNumTextActionPerformed

    private void usrnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnametextActionPerformed
       if(!ValidateInputs.isUsernameValid( usrnametext.getText())){
           JOptionPane.showMessageDialog(this, "Enter Username correctly");
       }
    }//GEN-LAST:event_usrnametextActionPerformed

    private void emailIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTextActionPerformed
        if( !ValidateInputs.isEmailValid(emailIdText.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailIdTextActionPerformed
     private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nametext.getText()) && ValidateInputs.isUsernameValid(usrnametext.getText()) && 
                ValidateInputs.isEmailValid(emailIdText.getText()) && ValidateInputs.isPhoneNumberValid(phoneNumText.getText())
                && ValidateInputs.isPasswordValid(psswordText.getText()) && ValidateInputs.isAddressValid(addrssText.getText()))  {
         return true; 
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrssLbl;
    private javax.swing.JTextField addrssText;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailIdText;
    private javax.swing.JLabel emailIdTxt;
    private javax.swing.JLabel headerCityNameLbl;
    private javax.swing.JLabel headerCityTagLbl;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel passLbl;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JTextField phoneNumText;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField psswordText;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField usrnametext;
    // End of variables declaration//GEN-END:variables

}
