/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.donationDealerWorkArea;


import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.enums.OrganizationType;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import StudentSale.organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshila
 */
public class UpdateOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private Organization org;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private User userAccount;
    
     private String imagePath;

    public UpdateOrganizationJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, CityNetwork cityNetwork, Organization org, User userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.org = org;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        Imagelbl.setSize(126, 139);
        
        populateData();
        populateCityHeader();
    }
    
    private void populateCityHeader(){
        headerCityNameLbl.setText(cityNetwork.getCityName().name());
    }
    
    private void setDefaultPhoto() {
        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }
    
     private void populateData() {
        
        orgNametext.setText(org.getOrganizationName());
        emailIdtext.setText(org.getEmail());
        addrsstext.setText(org.getAddress());
        phoneNumtext.setText(org.getPhoneNo());
        imagePath = org.getOrganizationImage();
        
        String[] organizationTypes  = OrganizationType.getOrganizationTypesArray();
        orgTypecombo.removeAllItems();
        for(String organizationType: organizationTypes) {
            orgTypecombo.addItem(organizationType);
        }
        
       orgTypecombo.setSelectedItem(org.getOrganizationType().name());
        
        setPhoto(imagePath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addrsstext = new javax.swing.JTextField();
        phoneNumtext = new javax.swing.JTextField();
        emailIdtext = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        orgName = new javax.swing.JLabel();
        orgType = new javax.swing.JLabel();
        orgAddress = new javax.swing.JLabel();
        orgPhoneNum = new javax.swing.JLabel();
        emailIdText = new javax.swing.JLabel();
        orgNametext = new javax.swing.JTextField();
        orgTypecombo = new javax.swing.JComboBox<>();
        Imagelbl = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        headerOrgText = new javax.swing.JLabel();
        headerCityTagLbl = new javax.swing.JLabel();
        headerCityNameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("DesktopIcon.background"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addrsstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrsstextActionPerformed(evt);
            }
        });
        add(addrsstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 160, 31));

        phoneNumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumtextActionPerformed(evt);
            }
        });
        add(phoneNumtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 160, 31));

        emailIdtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdtextActionPerformed(evt);
            }
        });
        add(emailIdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 160, 31));

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        orgName.setText("Organization Name:");
        add(orgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        orgType.setText("Organization Type:");
        add(orgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 31));

        orgAddress.setText("Address:");
        add(orgAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 109, 31));

        orgPhoneNum.setText("Phone Number:");
        add(orgPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 109, 31));

        emailIdText.setText("Email Id:");
        add(emailIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 109, 34));

        orgNametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgNametextActionPerformed(evt);
            }
        });
        add(orgNametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 160, 31));

        orgTypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTypecomboActionPerformed(evt);
            }
        });
        add(orgTypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, 31));

        Imagelbl.setText("<Image>");
        Imagelbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(Imagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 108, 124));

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        headerOrgText.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        headerOrgText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerOrgText.setText("Update Organization");
        add(headerOrgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 20, 301, 29));

        headerCityTagLbl.setText("City:");
        add(headerCityTagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 20, -1, 30));
        add(headerCityNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 20, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orgNametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgNametextActionPerformed
        if(!ValidateInputs.isNameValid(orgNametext.getText())){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_orgNametextActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] components = userProcessContainer.getComponents();
        ManageOrganizationJPanel manageOrgJPanel = (ManageOrganizationJPanel) components[components.length-1];
        manageOrgJPanel.populateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        if(isDataEnteredValid()) {

            if(!org.getEmail().equals(emailIdtext.getText()) && EmailHelper.isEmailAlreadyExisted(ecoSystem, emailIdtext.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            if(!org.getPhoneNo().equals(phoneNumtext.getText()) && PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phoneNumtext.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }
            
            org.setOrganizationName(orgNametext.getText());
            org.setEmail(emailIdtext.getText());
            org.setPhoneNo(phoneNumtext.getText());
            org.setAddress(addrsstext.getText());
            org.setOrganizationImage(imagePath);
            org.setOrganizationType(OrganizationType.valueOf((String) orgTypecombo.getSelectedItem()));

            JOptionPane.showMessageDialog(this, "Successfully saved new Organization");
        }else{
            JOptionPane.showMessageDialog(this, "Error saving new Organization. Please check DataTypes");
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void orgTypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTypecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTypecomboActionPerformed

    private void addrsstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrsstextActionPerformed
       if(!ValidateInputs.isAddressValid(addrsstext.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_addrsstextActionPerformed

    private void phoneNumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumtextActionPerformed
         if( !ValidateInputs.isPhoneNumberValid(phoneNumtext.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phoneNumtextActionPerformed

    private void emailIdtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdtextActionPerformed
        if( !ValidateInputs.isEmailValid(emailIdtext.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailIdtextActionPerformed
    private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(orgNametext.getText()) && 
                ValidateInputs.isEmailValid(emailIdtext.getText()) && 
                ValidateInputs.isPhoneNumberValid(phoneNumtext.getText()))  {
           return true; 
        }
        return false;
    }   
    
    private void setPhoto(String imagePath) {
        if(imagePath.equals(Constants.DEFAULT_PROFILE_IMAGE_PATH)) {
            ImageIcon photo = new ImageIcon(Paths.get(Constants.DEFAULT_PROFILE_IMAGE_PATH).toAbsolutePath().toString());
            Image photoResized = photo.getImage().getScaledInstance(Imagelbl.getWidth(), Imagelbl.getHeight(),4);
            Imagelbl.setIcon(new ImageIcon(photoResized));
            return;
        }
        
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(Imagelbl.getWidth(), Imagelbl.getHeight(),4);
        Imagelbl.setIcon(new ImageIcon(photoResized));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagelbl;
    private javax.swing.JTextField addrsstext;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel emailIdText;
    private javax.swing.JTextField emailIdtext;
    private javax.swing.JLabel headerCityNameLbl;
    private javax.swing.JLabel headerCityTagLbl;
    private javax.swing.JLabel headerOrgText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel orgAddress;
    private javax.swing.JLabel orgName;
    private javax.swing.JTextField orgNametext;
    private javax.swing.JLabel orgPhoneNum;
    private javax.swing.JLabel orgType;
    private javax.swing.JComboBox<String> orgTypecombo;
    private javax.swing.JTextField phoneNumtext;
    private javax.swing.JButton updatebutton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
