/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.signUpWorkArea;

import StudentSale.DB4OUtil.DB4OUtil;
import StudentSale.EcoSystem;
import StudentSale.std.Student;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import StudentSale.email.EmailUtil;

/**
 *
 * @author sishwathoka
 */
public class SignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessJPanel;
    private EcoSystem ecoSystem;
    private ImageIcon iconPic;
    private DB4OUtil dB4OUtil;
    private String photoPath = Constants.DEFAULT_PROFILE_IMAGE_PATH;
    private String verificationCode ;
    private static final Logger logger = Logger.getLogger(SignUpJPanel.class.getName());
    private Student std;
    private Boolean check;

    /**
     * Creates new form SignUpJPanel
     */
    public SignUpJPanel(JPanel userProcessJPanel, EcoSystem ecoSystem, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessJPanel = userProcessJPanel;
        this.ecoSystem = ecoSystem;
        this.dB4OUtil = dB4OUtil;
        picpreviewLbl.setSize(126, 139);
        setDefaultPhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        UsernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        txtphonenoTxtFld = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textUsername = new javax.swing.JTextField();
        txtpsswrd = new javax.swing.JTextField();
        createUserBtn = new javax.swing.JButton();
        btnAttachPic = new javax.swing.JButton();
        picpreviewLbl = new javax.swing.JLabel();
        addrssLbl = new javax.swing.JLabel();
        textaddrss = new javax.swing.JTextField();
        btnverify = new javax.swing.JButton();
        txtVerificationCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signupbutton.gif"))); // NOI18N
        titleLbl.setText("Create New User");
        add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 528, 73));

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 15, 116, -1));

        nameLbl.setText("Name");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 261, 130, 29));

        lblPhoneNum.setText("Phone Number");
        add(lblPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 374, 130, 29));

        emailLbl.setText("Email");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 434, 130, 29));

        UsernameLbl.setText("User Name");
        add(UsernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 493, 130, 29));

        passwordLbl.setText("Password");
        add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 552, 130, 29));

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 261, 176, 29));

        txtphonenoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoTxtFldActionPerformed(evt);
            }
        });
        add(txtphonenoTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 374, 176, 29));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 434, 176, 29));

        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });
        add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 493, 176, 29));

        txtpsswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpsswrdActionPerformed(evt);
            }
        });
        add(txtpsswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 552, 176, 29));

        createUserBtn.setText("Create");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        add(createUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 753, -1, -1));

        btnAttachPic.setText("Attach Pic");
        btnAttachPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachPicActionPerformed(evt);
            }
        });
        add(btnAttachPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 224, -1, -1));

        picpreviewLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picpreviewLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 265, 134, 138));

        addrssLbl.setText("Address");
        add(addrssLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 317, 130, 29));

        textaddrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textaddrssActionPerformed(evt);
            }
        });
        add(textaddrss, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 317, 176, 29));

        btnverify.setText("Send Verification OTP");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 624, 176, -1));

        txtVerificationCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerificationCodeActionPerformed(evt);
            }
        });
        add(txtVerificationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 683, 176, -1));

        jLabel1.setText("Enter OTP");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 689, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Screen Shot 2022-12-15 at 8.48.49 AM.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -330, -1, 1370));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Back button pressed");
        CardLayout layout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.remove(this);
        layout.previous(userProcessJPanel);

        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnAttachPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachPicActionPerformed
        JFileChooser image = new JFileChooser();
        FileNameExtensionFilter nameFilter = new FileNameExtensionFilter("jpeg", "jpg", "png");
        image.addChoosableFileFilter(nameFilter);
        int dlgBox = image.showOpenDialog(null);

        if (dlgBox == JFileChooser.APPROVE_OPTION) {
            File f = image.getSelectedFile();
            this.photoPath = f.getAbsolutePath();
            ImageIcon icon = new ImageIcon(photoPath);
            this.iconPic = icon;
        }

        if (iconPic != null) {
            Image resizedImage = iconPic.getImage().getScaledInstance(picpreviewLbl.getWidth(), picpreviewLbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon resizedIconPic = new ImageIcon(resizedImage);
            picpreviewLbl.setIcon(resizedIconPic);
            JOptionPane.showMessageDialog(this, "Image Successfully Uploaded");
        }
    }//GEN-LAST:event_btnAttachPicActionPerformed

    private void txtVerificationCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerificationCodeActionPerformed
        // TODO add your handling code here:
        
        if (txtVerificationCode.getText().equals(verificationCode)) {
            JOptionPane.showMessageDialog(this, "Email has been verified.");
            check =true;
        } else {
            JOptionPane.showMessageDialog(this, "Enter correct verification code.");
        }
        txtVerificationCode.setText("");
    }//GEN-LAST:event_txtVerificationCodeActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        // TODO add your handling code here:
        try {
            verificationCode = EmailUtil.getRandomCode();
            EmailUtil.sendMail(textEmail.getText(), textName.getText(), verificationCode);
        } catch (Exception ex) {
        }
        JOptionPane.showMessageDialog(this, "Verification OTP sent to the user at the email address provided.");

    }//GEN-LAST:event_btnverifyActionPerformed

    private void textaddrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textaddrssActionPerformed
        if(!ValidateInputs.isAddressValid(textaddrss.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
    }//GEN-LAST:event_textaddrssActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
       if(!ValidateInputs.isNameValid(textName.getText()) || textName.getText().length() < 8){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_textNameActionPerformed

    private void txtpsswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpsswrdActionPerformed
        if( !ValidateInputs.isPasswordValid(txtpsswrd.getText())){
                   JOptionPane.showMessageDialog(this, "Enter password correctly(minimum 8 digits)");

       }
    }//GEN-LAST:event_txtpsswrdActionPerformed

    private void txtphonenoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoTxtFldActionPerformed
       if( !ValidateInputs.isPhoneNumberValid(txtphonenoTxtFld.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_txtphonenoTxtFldActionPerformed

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
         if(!ValidateInputs.isUsernameValid(textUsername.getText())){
           JOptionPane.showMessageDialog(this, "Enter Username correctly");
       }
    }//GEN-LAST:event_textUsernameActionPerformed

    private void resetFields() {
        textName.setText("");
        textUsername.setText("");
        txtpsswrd.setText("");
        textEmail.setText("");
        txtphonenoTxtFld.setText("");
        textaddrss.setText("");
        txtVerificationCode.setText("");

        setDefaultPhoto();
    }

    private void setDefaultPhoto() {

        setPhoto(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
    }

    private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(picpreviewLbl.getWidth(), picpreviewLbl.getHeight(), 4);
        picpreviewLbl.setIcon(new ImageIcon(photoResized));
    }

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (UserNameHelper.isUserNameAlreadyExisted(ecoSystem, textUsername.getText())) {
            JOptionPane.showMessageDialog(this, "User Name already registered. Please try with a different User Name");
            return;
        }

        if (EmailHelper.isEmailAlreadyExisted(ecoSystem, textEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Email already registered. Please try with a different Email");
            return;
        }

        if (PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, txtphonenoTxtFld.getText())) {
            JOptionPane.showMessageDialog(this, "Phone Number already registered. Please try with a different Phone Number");
            return;
        }

        if (ValidateInputs.isNameValid(textName.getText()) && ValidateInputs.isPhoneNumberValid(txtphonenoTxtFld.getText())
                && ValidateInputs.isEmailValid(textEmail.getText()) && ValidateInputs.isUsernameValid(textUsername.getText())
                && ValidateInputs.isPasswordValid(txtpsswrd.getText()) && ValidateInputs.isAddressValid(textaddrss.getText())) {

           if(check){
                std = new Student(textName.getText(), txtphonenoTxtFld.getText(), textEmail.getText(), textaddrss.getText(), textUsername.getText(),
                    txtpsswrd.getText(), StudentRole.Student, photoPath, new Date(), new Date(), textName.getText(), textName.getText());

            ecoSystem.getDonorsDirectory().getDonors().add(std);

            JOptionPane.showMessageDialog(this, "User successfully registered and a confirmation email has been sent");
            resetFields();
           }
        } else {
            JOptionPane.showMessageDialog(this, "Please verify all the data types as per fields.");
        }
    }

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {
        if( !ValidateInputs.isEmailValid(textEmail.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JLabel addrssLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAttachPic;
    private javax.swing.JButton btnverify;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel picpreviewLbl;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textUsername;
    private javax.swing.JTextField textaddrss;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField txtVerificationCode;
    private javax.swing.JTextField txtphonenoTxtFld;
    private javax.swing.JTextField txtpsswrd;
    // End of variables declaration//GEN-END:variables
}
