/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.studentWorkArea;

import StudentSale.CityNetwork;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.std.Donation;
import StudentSale.std.Student;
import StudentSale.enums.Category;
import StudentSale.enums.DonationStatus;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sishwathoka
 */
public class ManageMyDonationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminHomeJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private Student std;
    private static final Logger logger = Logger.getLogger(ManageMyDonationsJPanel.class.getName());
    
    public ManageMyDonationsJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        this.std = (Student) userLogged;

        populateCategories();
        populateDonationHistoryTable();
    }
    
    public void populateCategories() {
        
        donationcatgoryCmbBx.removeAllItems();
        String[] categories = Category.getCategoriesArray();
        for(String category:categories) {
            donationcatgoryCmbBx.addItem(category);
        }
    }
    
    
    public void populateDonationHistoryTable() {
        
//        int selectedIndex = donationcategoryjComboBox.getSelectedIndex();
//        if(selectedIndex<0) {
//            JOptionPane.showMessageDialog(this, "Please select a category to proceed further");
//            return;
//        }
//        
//        int selectedIndex2 = cityjComboBox.getSelectedIndex();
//        if(selectedIndex2<0) {
//            JOptionPane.showMessageDialog(this, "Please select a city to proceed further");
//            return;
//        }
        
        DefaultTableModel donationHistory = (DefaultTableModel) donationHistoryLbl.getModel();
        donationHistory.setRowCount(0);
        
        int donationsCount=0;
        for(Donation donation:std.getDonations()) {
            if (donation.getCategory().name().equalsIgnoreCase(donationcatgoryCmbBx.getSelectedItem().toString())){
            donationsCount++;
            Object[] row = new Object[9];
            row[0]=donationsCount;
            row[1]=donation.getDonor().getName();
            row[2]=donation;
            row[3]=donation.getUsageStatus();
            row[4]=donation.getDonationStatus();
            row[5]=donation.getAddressToPickUp();
            row[6]=donation.getCityNetwork().getCityName().name();;
            row[7]=donation.getDeliveryVolunteer()==null?"Not yet assigned":donation.getDeliveryVolunteer().getName();
            row[8]=donation.getOrganization()==null?"Not yet assigned":donation.getOrganization();
            donationHistory.addRow(row);
            }
        }
        countTtlLbl.setText(String.valueOf(donationsCount));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donationcatgoryCmbBx = new javax.swing.JComboBox<>();
        makeDonationBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationHistoryLbl = new javax.swing.JTable();
        countTtlLbl = new javax.swing.JLabel();
        countLbl = new javax.swing.JLabel();
        donationCategoryLbl = new javax.swing.JLabel();
        headerLbl = new javax.swing.JLabel();
        viewOrUpdateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donationcatgoryCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationcatgoryCmbBxActionPerformed(evt);
            }
        });
        add(donationcatgoryCmbBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 224, -1));

        makeDonationBtn.setText("Make New Donation >>");
        makeDonationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeDonationBtnActionPerformed(evt);
            }
        });
        add(makeDonationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 180, -1));

        donationHistoryLbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Student", "Information", "Usage Status", "Status", "To be PickedUp at", "City", "Delivery Volunteer", "Sent To (Org)"
            }
        ));
        jScrollPane1.setViewportView(donationHistoryLbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 950, 170));

        countTtlLbl.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countTtlLbl.setText("0");
        add(countTtlLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        countLbl.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countLbl.setText("Count :");
        add(countLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        donationCategoryLbl.setText("Donation Category:");
        add(donationCategoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 20));

        headerLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 190, 30));

        viewOrUpdateBtn.setText("View/Update");
        viewOrUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrUpdateBtnActionPerformed(evt);
            }
        });
        add(viewOrUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 120, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 120, -1));

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void makeDonationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeDonationBtnActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("MakeNewDonationJPanel",new CreateNewDonationJPanel(userProcessJpanel,ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_makeDonationBtnActionPerformed

    private void donationcatgoryCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationcatgoryCmbBxActionPerformed
        populateDonationHistoryTable();
    }//GEN-LAST:event_donationcatgoryCmbBxActionPerformed

    private void viewOrUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrUpdateBtnActionPerformed
        int selectedRow = donationHistoryLbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }else {
            Donation selectedDonation = (Donation) donationHistoryLbl.getValueAt(selectedRow, 2);
            
            if(selectedDonation.getDonationStatus().equals(DonationStatus.Closed)){
                JOptionPane.showMessageDialog(this, "This donation request is already Closed. Cannot edit now.");
                return;
            }
            
            if (selectedDonation.getDonationStatus().equals(DonationStatus.PickedUp)){
                JOptionPane.showMessageDialog(this, "This donation request is already Picked up. Cannot edit now.");
                return;
            }
            
            if (selectedDonation.getDonationStatus().equals(DonationStatus.Accepted)){
                JOptionPane.showMessageDialog(this, "This donation request is already Accepted. Cannot edit now.");
                return;
            }
            
            CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
            userProcessJpanel.add("ViewOrEditDonationJPanel",new ViewOrEditDonationJPanel(userProcessJpanel,ecoSystem, userLogged, selectedDonation));
            cardLayout.next(userProcessJpanel);
        }
    }//GEN-LAST:event_viewOrUpdateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = donationHistoryLbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }else {
            Donation selectedDonation = (Donation) donationHistoryLbl.getValueAt(selectedRow, 2);
            if (!selectedDonation.getDonationStatus().equals(DonationStatus.ReadyToPickup)){
                JOptionPane.showMessageDialog(this, "!Error! You can only delete when the donation status is Ready for Pickup");
            }else{
                std.getDonations().remove(selectedDonation);
                JOptionPane.showMessageDialog(this, "Donation request deleted successfully");
                logger.log(Level.INFO, "Donation deleted");
                populateDonationHistoryTable();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessJpanel.remove(this);

        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel countLbl;
    private javax.swing.JLabel countTtlLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel donationCategoryLbl;
    private javax.swing.JTable donationHistoryLbl;
    private javax.swing.JComboBox<String> donationcatgoryCmbBx;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeDonationBtn;
    private javax.swing.JButton viewOrUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
