/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.studentWorkArea;

import StudentSale.DB4OUtil.DB4OUtil;
import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.serviceAgent.ServiceAgent;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import java.awt.CardLayout;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import userinterface.donationDealerWorkArea.ViewAssignedDriverJPanel;
import userinterface.donationDealerWorkArea.ViewAssignedPackingAgentJPanel;

/**
 *
 * @author sahithreddy
 */
public class StudentHomeJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessJPanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private static final Logger logger = Logger.getLogger(StudentHomeJPanel.class.getName()); 
        
    
    /**
     * Creates new form DonorHomeJPanel
     */
    public StudentHomeJPanel(JPanel userProcessJPanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        
        this.userProcessJPanel = userProcessJPanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
//        ServiceAgent c = new ServiceAgent("Michael Murugesh", "8463512357", "mmcleaner@gmail.com", "110 Forest Hills, Boston", "cleaner1", "password", StudentRole.Donor, Constants.DEFAULT_PROFILE_IMAGE_PATH, new Date(), new Date(), "Guna", "Guna");
//        ecoSystem.getCityNetworkDirectory().getCityNetworks().get(1).getCleanersDirectory().getCleaners().add(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        updateMyProfileLbl = new javax.swing.JButton();
        manageMyDonationBtn = new javax.swing.JButton();
        viewAssignedPackingAgentjButton1 = new javax.swing.JButton();
        viewAssignedjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setText("Student Home Page");
        add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 240, 27));

        updateMyProfileLbl.setText("Update My Profile");
        updateMyProfileLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMyProfileLblActionPerformed(evt);
            }
        });
        add(updateMyProfileLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 101, 230, -1));

        manageMyDonationBtn.setText("Manage My Donations");
        manageMyDonationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMyDonationBtnActionPerformed(evt);
            }
        });
        add(manageMyDonationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        viewAssignedPackingAgentjButton1.setText("View Assigned Packing Agent");
        viewAssignedPackingAgentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAssignedPackingAgentjButton1ActionPerformed(evt);
            }
        });
        add(viewAssignedPackingAgentjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 250, -1));

        viewAssignedjButton2.setText("View Assigned Driver");
        viewAssignedjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAssignedjButton2ActionPerformed(evt);
            }
        });
        add(viewAssignedjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Mainpage.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 780, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateMyProfileLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMyProfileLblActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("UpdateDonorProfileJPanel", new UpdateStudentProfileJPanel(userProcessJPanel,ecoSystem,userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_updateMyProfileLblActionPerformed

    private void manageMyDonationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMyDonationBtnActionPerformed
        logger.log(Level.INFO, "Entering into Manage My Donations Screen");
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("ManageMyDonationsJPanel", new ManageMyDonationsJPanel(userProcessJPanel,ecoSystem,userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_manageMyDonationBtnActionPerformed

    private void viewAssignedPackingAgentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAssignedPackingAgentjButton1ActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Entering into View Assigned Packing Agent Screen");
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("ViewAssignedPackingAgent", new ViewAssignedPackingAgentJPanel(userProcessJPanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_viewAssignedPackingAgentjButton1ActionPerformed

    private void viewAssignedjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAssignedjButton2ActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "Entering into View Assigned Driver Screen");
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("ViewAssignedDriver", new ViewAssignedDriverJPanel(userProcessJPanel, ecoSystem, userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_viewAssignedjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageMyDonationBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateMyProfileLbl;
    private javax.swing.JButton viewAssignedPackingAgentjButton1;
    private javax.swing.JButton viewAssignedjButton2;
    // End of variables declaration//GEN-END:variables
}
