/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.studentWorkArea;

import StudentSale.EcoSystem;
import StudentSale.User;
import StudentSale.enums.StudentRole;
import StudentSale.helper.Constants;
import StudentSale.helper.EmailHelper;
import StudentSale.helper.PhoneNoHelper;
import StudentSale.helper.UserNameHelper;
import StudentSale.helper.ValidateInputs;
import StudentSale.sysAdmin.SysAdmin;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.nio.file.Paths;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sishwathoka
 */
public class UpdateStudentProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateSysAdminJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private String imagePath;
    private static final Logger logger = Logger.getLogger(UpdateStudentProfileJPanel.class.getName());
    
    public UpdateStudentProfileJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        
        picLabel.setSize(126, 139);
        populateData();
    }

    private void populateData() {
        
        nameTxtFld.setText(userLogged.getName());
        usrNameTxtFld.setText(userLogged.getUserName());
        passwdTxtFld.setText(userLogged.getPassword());
        phoneNumTxtFld.setText(userLogged.getPhoneNo());
        emailTxtFld.setText(userLogged.getEmail());
        addTxtFld.setText(userLogged.getAddress());
        imagePath = userLogged.getProfilePic();
        
        setPhoto(userLogged.getProfilePic());
    }
    
    private void setPhoto(String photo) {
        
        if(photo.equals(Constants.DEFAULT_PROFILE_IMAGE_PATH)) {
            ImageIcon pic = new ImageIcon(getClass().getResource(Constants.DEFAULT_PROFILE_IMAGE_PATH).getPath());
            Image photoResized = pic.getImage().getScaledInstance(picLabel.getWidth(), picLabel.getHeight(),4);
            picLabel.setIcon(new ImageIcon(photoResized));
            return;
        }
 
        ImageIcon pic = new ImageIcon(photo);
        Image photoResized = pic.getImage().getScaledInstance(picLabel.getWidth(), picLabel.getHeight(),4);
        picLabel.setIcon(new ImageIcon(photoResized));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        phoneNumTxtFld = new javax.swing.JTextField();
        headerLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        usrNameTxtFld = new javax.swing.JTextField();
        usrNameLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        addLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        addTxtFld = new javax.swing.JTextField();
        passwdTxtFld = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        picLabel = new javax.swing.JLabel();
        emailTxtFld = new javax.swing.JTextField();
        uploadBttn = new javax.swing.JButton();
        phoneNumLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("SlidingButton.selectedBackground"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("< < Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 41, -1, -1));

        phoneNumTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTxtFldActionPerformed(evt);
            }
        });
        add(phoneNumTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 346, 234, 40));

        headerLbl.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("Update Student Profile");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 34, 415, 34));

        nameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("Name :");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 111, 122, 40));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 488, -1, -1));

        usrNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrNameTxtFldActionPerformed(evt);
            }
        });
        add(usrNameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 171, 234, 40));

        usrNameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        usrNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usrNameLbl.setText("User Name :");
        add(usrNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 169, 122, 40));

        nameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFldActionPerformed(evt);
            }
        });
        add(nameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 113, 234, 40));

        addLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLbl.setText("Address :");
        add(addLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 402, 122, 40));

        passLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        passLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLbl.setText("Password :");
        add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 229, 122, 40));

        addTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtFldActionPerformed(evt);
            }
        });
        add(addTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 400, 234, 40));

        passwdTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdTxtFldActionPerformed(evt);
            }
        });
        add(passwdTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 229, 234, 40));

        emailLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLbl.setText("Email :");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 287, 122, 40));

        picLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 150, 126, 139));

        emailTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFldActionPerformed(evt);
            }
        });
        add(emailTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 288, 234, 40));

        uploadBttn.setText("upload");
        uploadBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBttnActionPerformed(evt);
            }
        });
        add(uploadBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        phoneNumLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        phoneNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneNumLbl.setText("Phone No :");
        add(phoneNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 348, 122, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessJpanel.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        cardLayout.previous(userProcessJpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(isDataEnteredValid()) {

            if(!userLogged.getUserName().equals(usrNameTxtFld.getText()) && UserNameHelper.isUserNameAlreadyExisted(ecoSystem, usrNameTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "UserName already Exists in the Ecosystem.");
                return;
            }
            if(!userLogged.getEmail().equals(emailTxtFld.getText()) && EmailHelper.isEmailAlreadyExisted(ecoSystem, emailTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "Email already Exists in the Ecosystem.");
                return;
            }
            if(!userLogged.getPhoneNo().equals(phoneNumTxtFld.getText()) && PhoneNoHelper.isPhoneNoAlreadyExisted(ecoSystem, phoneNumTxtFld.getText())) {
                JOptionPane.showMessageDialog(this, "PhoneNo already Exists in the Ecosystem.");
                return;
            }

            userLogged.setName(nameTxtFld.getText());
            userLogged.setUserName(usrNameTxtFld.getText());
            userLogged.setPassword(passwdTxtFld.getText());
            userLogged.setEmail(emailTxtFld.getText());
            userLogged.setPhoneNo(phoneNumTxtFld.getText());
            userLogged.setAddress(addTxtFld.getText());
            userLogged.setProfilePic(imagePath);
            userLogged.setLastUpdatedDate(new Date());
            userLogged.setModifiedBy(userLogged.getUserName());
            JOptionPane.showMessageDialog(this, "Successfully updated the Donor Profile");
            logger.log(Level.INFO, "Donor Profile Update Successful");
        }else{
            JOptionPane.showMessageDialog(this, "Error saving Donor Profile. Please check DataTypes");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private boolean isDataEnteredValid() {
        if(ValidateInputs.isNameValid(nameTxtFld.getText()) && ValidateInputs.isUsernameValid(usrNameTxtFld.getText()) && 
                ValidateInputs.isEmailValid(emailTxtFld.getText()) && ValidateInputs.isPhoneNumberValid(phoneNumTxtFld.getText())
                && ValidateInputs.isPasswordValid(passwdTxtFld.getText()) && ValidateInputs.isAddressValid(addTxtFld.getText()))  {
           return true; 
        }
        return false;
    }
    
    private void uploadBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBttnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("/"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpeg format", "jpeg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Jpg format", "jpg"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Png format", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            setPhoto(imagePath);
        }
    }//GEN-LAST:event_uploadBttnActionPerformed

    private void phoneNumTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isPhoneNumberValid(phoneNumTxtFld.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter phoneNumber correctly with minimum 10 digits)");

       }
    }//GEN-LAST:event_phoneNumTxtFldActionPerformed

    private void nameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFldActionPerformed
        // TODO add your handling code here:
        if(!ValidateInputs.isNameValid(nameTxtFld.getText()) ){
           JOptionPane.showMessageDialog(this, "Enter Name correctly");
       }
    }//GEN-LAST:event_nameTxtFldActionPerformed

    private void usrNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrNameTxtFldActionPerformed
        // TODO add your handling code here:
        if(!ValidateInputs.isUsernameValid(usrNameTxtFld.getText())){
           JOptionPane.showMessageDialog(this, "Enter Username correctly");
       }
        
    }//GEN-LAST:event_usrNameTxtFldActionPerformed

    private void passwdTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isPasswordValid(passwdTxtFld.getText())){
                   JOptionPane.showMessageDialog(this, "Enter password correctly(minimum 8 digits)");

       }
    }//GEN-LAST:event_passwdTxtFldActionPerformed

    private void emailTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFldActionPerformed
        // TODO add your handling code here:
        if( !ValidateInputs.isEmailValid(emailTxtFld.getText()))
               {
                   JOptionPane.showMessageDialog(this, "Enter Email correctly");

       }
    }//GEN-LAST:event_emailTxtFldActionPerformed

    private void addTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtFldActionPerformed
        // TODO add your handling code here:
        if(!ValidateInputs.isAddressValid(addTxtFld.getText())){
           JOptionPane.showMessageDialog(this, "Enter Address correctly");
       }
        
    }//GEN-LAST:event_addTxtFldActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLbl;
    private javax.swing.JTextField addTxtFld;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JLabel passLbl;
    private javax.swing.JTextField passwdTxtFld;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JTextField phoneNumTxtFld;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uploadBttn;
    private javax.swing.JLabel usrNameLbl;
    private javax.swing.JTextField usrNameTxtFld;
    // End of variables declaration//GEN-END:variables
}
